Repository 29ki/29k, pull requests merged in 2022-09, with the labels that each got.

#309 Update exercise “095f9642-73b6-4c9a-ae9a-ea7dea7363f5”
  content/src/exercises/095f9642-73b6-4c9a-ae9a-ea7dea7363f5.json
Labels: netlify-cms/draft

#337 Update exercise “095f9642-73b6-4c9a-ae9a-ea7dea7363f5”
  content/src/exercises/095f9642-73b6-4c9a-ae9a-ea7dea7363f5.json
Labels: netlify-cms/pending_publish

#344 Update exercise “095f9642-73b6-4c9a-ae9a-ea7dea7363f5”
  content/src/exercises/095f9642-73b6-4c9a-ae9a-ea7dea7363f5.json
Labels: netlify-cms/pending_publish

#346 Update exercise “095f9642-73b6-4c9a-ae9a-ea7dea7363f5”
  content/src/exercises/095f9642-73b6-4c9a-ae9a-ea7dea7363f5.json
Labels: netlify-cms/pending_publish

#347 Update exercise “095f9642-73b6-4c9a-ae9a-ea7dea7363f5”
  content/src/exercises/095f9642-73b6-4c9a-ae9a-ea7dea7363f5.json
Labels: netlify-cms/pending_publish

#414 Update UI “Component.ConfirmExitTemple”
  content/src/ui/Component.ConfirmExitTemple.json
Labels: netlify-cms/pending_publish

#415 Update UI “Screen.Temples”
  content/src/ui/Screen.Temples.json
Labels: netlify-cms/pending_publish

#416 Update UI “Screen.Temples”
  content/src/ui/Screen.Temples.json
Labels: netlify-cms/pending_publish

#419 🚢 Release 2.0.12
  client/android/app/build.gradle
  client/ios/Supporting/Info.plist
  client/ios/twentyninek.xcodeproj/project.pbxproj
  client/ios/twentyninek/AppDelegate.mm
Labels: native release

#437 Improve local development
  client/index.js
  client/ios/Supporting/Info.plist
  client/package.json
  client/scripts/getHostname.sh
  firebase.json
Labels: native release

#438 Correct iOS Development Team
  client/ios/twentyninek.xcodeproj/project.pbxproj
Labels: native release

#466 Notification reminders
  client/__mocks__/@notifee/react-native.js
  client/__mocks__/react-i18next.js
  client/android/build.gradle
  client/ios/Podfile.lock
  client/jest.config.js
  client/package.json
  client/src/common/components/Cards/Card.tsx
  client/src/common/components/Cards/Cards.library.tsx
  client/src/common/components/Cards/TempleCard/TempleCard.tsx
  client/src/common/components/Icons/Bell/Bell.tsx
  client/src/common/components/Icons/index.ts
  client/src/lib/i18n/constants/namespaces.ts
  client/src/lib/navigation/Stacks.tsx
  client/src/lib/notifications/hooks/useTriggerNotification.spec.ts
  client/src/lib/notifications/hooks/useTriggerNotification.ts
  client/src/lib/notifications/state/state.spec.ts
  client/src/lib/notifications/state/state.ts
  client/src/routes/Temples/components/TempleModal.tsx
  client/src/routes/Temples/hooks/useTempleNotificationReminder.spec.ts
  client/src/routes/Temples/hooks/useTempleNotificationReminder.ts
  client/yarn.lock
  content/src/ui/Component.SessionReminder.json
  content/src/ui/Component.TempleModal.json
Labels: native release
