Repository 29ki/29k, pull requests merged in 2022-12, with the labels that each got.

#1151 Update 📱 UI “Screen.Welcome”
  content/src/ui/Screen.Welcome.json
Labels: netlify-cms/pending_publish

#1156 Update 📱 UI “Modal.CreateSession”
  content/src/ui/Modal.CreateSession.json
Labels: netlify-cms/pending_publish

#1153 Update 📱 UI “Component.CodePushOverlay”
  content/src/ui/Component.CodePushOverlay.json
Labels: netlify-cms/pending_publish

#1158 Update 📱 UI “Screen.ChangingRoom”
  content/src/ui/Screen.ChangingRoom.json
Labels: netlify-cms/pending_publish

#1157 Update 📱 UI “Modal.UpgradeAccount”
  content/src/ui/Modal.UpgradeAccount.json
Labels: netlify-cms/pending_publish

#1152 Update 📱 UI “Modal.Session”
  content/src/ui/Modal.Session.json
Labels: netlify-cms/pending_publish

#1155 Update 📱 UI “Modal.AddSession”
  content/src/ui/Modal.AddSession.json
Labels: netlify-cms/pending_publish

#1154 Update 📱 UI “Component.ConfirmExitSession”
  content/src/ui/Component.ConfirmExitSession.json
Labels: netlify-cms/pending_publish

#1179 Update 📱 UI “Screen.Profile”
  content/src/ui/Screen.Profile.json
Labels: netlify-cms/pending_publish

#1176 Update 📱 UI “DeepLink.JoinSessionInvite”
  content/src/ui/DeepLink.JoinSessionInvite.json
Labels: netlify-cms/pending_publish

#1174 Update 📱 UI “Component.SessionCard”
  content/src/ui/Component.SessionCard.json
Labels: netlify-cms/pending_publish

#1177 Update 📱 UI “Modal.Session”
  content/src/ui/Modal.Session.json
Labels: netlify-cms/pending_publish

#1173 Update 📱 UI “Component.DateTimePicker”
  content/src/ui/Component.DateTimePicker.json
Labels: netlify-cms/pending_publish

#1178 Update 📱 UI “Screen.Portal”
  content/src/ui/Screen.Portal.json
Labels: netlify-cms/pending_publish

#1180 Update 📱 UI “Screen.Session”
  content/src/ui/Screen.Session.json
Labels: netlify-cms/pending_publish

#1183 Update exercise “095f9642-73b6-4c9a-ae9a-ea7dea7363f5”
  content/src/exercises/095f9642-73b6-4c9a-ae9a-ea7dea7363f5.json
Labels: netlify-cms/pending_publish

#1182 Update exercise “185889ec-753b-4e2c-8322-3004013e8a6e”
  content/src/exercises/185889ec-753b-4e2c-8322-3004013e8a6e.json
Labels: netlify-cms/pending_publish

#1219 Update daily room expiry date when updating session startTime
  functions/src/controllers/sessions.spec.ts
  functions/src/controllers/sessions.ts
  functions/src/lib/dailyApi.spec.ts
  functions/src/lib/dailyApi.ts
Labels: bug

#1181 Update 📱 UI “Screen.Sessions”
  content/src/ui/Screen.Sessions.json
Labels: netlify-cms/pending_publish

#1175 Update 📱 UI “Component.SessionTimeBadge”
  content/src/ui/Component.SessionTimeBadge.json
Labels: netlify-cms/pending_publish

#1234 Update exercise “095f9642-73b6-4c9a-ae9a-ea7dea7363f5”
  content/src/exercises/095f9642-73b6-4c9a-ae9a-ea7dea7363f5.json
Labels: netlify-cms/pending_publish

#1167 🚢 Release 2.6.0
  client/android/app/build.gradle
  client/ios/Podfile.lock
  client/ios/Supporting/Info.plist
  client/ios/twentyninek.xcodeproj/project.pbxproj
  client/ios/twentyninek/AppDelegate.mm
  client/package.json
  client/src/lib/audio/components/Audio.tsx
  client/src/lib/audio/hooks/useAudio.ts
  client/src/routes/Session/IntroPortal.tsx
  client/src/routes/Session/components/AudioFader/AudioFader.tsx
  client/src/routes/Session/components/VideoBase/VideoBase.tsx
  client/yarn.lock
Labels: native release

#1284 Update 📱 UI “Modal.CreateSession”
  content/src/ui/Modal.CreateSession.json
Labels: netlify-cms/pending_publish

#1286 Update 📱 UI “Component.DeleteData”
  content/src/ui/Component.DeleteData.json
Labels: netlify-cms/pending_publish

#1278 Update 📱 UI “Screen.Profile”
  content/src/ui/Screen.Profile.json
Labels: netlify-cms/pending_publish

#1280 Update 📱 UI “Modal.Session”
  content/src/ui/Modal.Session.json
Labels: netlify-cms/pending_publish

#1281 Update 📱 UI “Modal.ProfileSettings”
  content/src/ui/Modal.ProfileSettings.json
Labels: netlify-cms/pending_publish

#1285 Update 📱 UI “Component.EditSessionType”
  content/src/ui/Component.EditSessionType.json
Labels: netlify-cms/pending_publish

#1279 Update 📱 UI “Modal.SignIn”
  content/src/ui/Modal.SignIn.json
Labels: netlify-cms/pending_publish

#1282 Update 📱 UI “Modal.JoinSession”
  content/src/ui/Modal.JoinSession.json
Labels: netlify-cms/pending_publish

#1289 Overlay navigation stack
  client/ios/Podfile.lock
  client/package.json
  client/src/lib/navigation/AppStack.tsx
  client/src/lib/navigation/ModalStack.tsx
  client/src/lib/navigation/OverlayStack.tsx
  client/src/lib/navigation/ProfileStack.tsx
  client/src/lib/navigation/SessionStack.tsx
  client/src/lib/navigation/Tabs.tsx
  client/src/lib/navigation/constants/routes.ts
  client/src/lib/navigation/linking.ts
  client/src/routes/AboutOverlay/AboutOverlay.tsx
  client/src/routes/Profile/Profile.tsx
  client/yarn.lock
Labels: native release

#1301 Update exercise “94575e97-fe03-4bfd-94a6-50aaf721d47e”
  content/src/exercises/94575e97-fe03-4bfd-94a6-50aaf721d47e.json
Labels: netlify-cms/pending_publish

#1276 🚢 Release 2.7.0
  client/android/app/build.gradle
  client/android/app/src/dev/res/values/strings.xml
  client/android/app/src/main/res/values/strings.xml
  client/android/app/src/production/res/values/strings.xml
  client/android/app/src/staging/res/values/strings.xml
  client/ios/Podfile.lock
  client/ios/Supporting/Info.plist
  client/ios/twentyninek.xcodeproj/project.pbxproj
  client/package.json
  client/src/lib/navigation/AppStack.tsx
  client/src/lib/navigation/ModalStack.tsx
  client/src/lib/navigation/OverlayStack.tsx
  client/src/lib/navigation/ProfileStack.tsx
  client/src/lib/navigation/SessionStack.tsx
  client/src/lib/navigation/Tabs.tsx
  client/src/lib/navigation/constants/routes.ts
  client/src/lib/navigation/linking.ts
  client/src/routes/AboutOverlay/AboutOverlay.tsx
  client/src/routes/Profile/Profile.tsx
  client/yarn.lock
Labels: native release

#1308 Update exercise “095f9642-73b6-4c9a-ae9a-ea7dea7363f5”
  content/src/exercises/095f9642-73b6-4c9a-ae9a-ea7dea7363f5.json
Labels: netlify-cms/pending_publish

#1306 Update exercise “ea0b48c1-745e-418d-93e7-2d8a6cd72898”
  content/src/exercises/ea0b48c1-745e-418d-93e7-2d8a6cd72898.json
Labels: netlify-cms/pending_publish

#1307 Update exercise “5b0dea9f-c665-41ce-a779-601d0cfa433d”
  content/src/exercises/5b0dea9f-c665-41ce-a779-601d0cfa433d.json
Labels: netlify-cms/pending_publish

#1305 Update exercise “94575e97-fe03-4bfd-94a6-50aaf721d47e”
  content/src/exercises/94575e97-fe03-4bfd-94a6-50aaf721d47e.json
Labels: netlify-cms/pending_publish

#1339 Update 📱 UI “DeepLink.JoinSessionInvite”
  content/src/ui/DeepLink.JoinSessionInvite.json
Labels: netlify-cms/pending_publish

#1340 Update 📱 UI “Modal.Session”
  content/src/ui/Modal.Session.json
Labels: netlify-cms/pending_publish

#1347 Create exercise “c5b1197a-4eec-4699-9dad-0e3d6323967b”
  content/src/exercises/c5b1197a-4eec-4699-9dad-0e3d6323967b.json
Labels: netlify-cms/pending_publish

#1352 Update 📱 UI “DeepLink.JoinSessionInvite”
  content/src/ui/DeepLink.JoinSessionInvite.json
Labels: netlify-cms/pending_publish

#1354 Create exercise “3188a5ed-a1d6-451c-ae2a-f44f4df37495”
  content/src/exercises/3188a5ed-a1d6-451c-ae2a-f44f4df37495.json
Labels: netlify-cms/pending_publish

#1357 Update exercise “ea0b48c1-745e-418d-93e7-2d8a6cd72898”
  content/src/exercises/ea0b48c1-745e-418d-93e7-2d8a6cd72898.json
Labels: netlify-cms/pending_publish

#1358 Update exercise “94575e97-fe03-4bfd-94a6-50aaf721d47e”
  content/src/exercises/94575e97-fe03-4bfd-94a6-50aaf721d47e.json
Labels: netlify-cms/pending_publish

#1342 🚢 Release 2.8.0
  client/android/app/build.gradle
  client/android/app/src/main/assets/modules.json
  client/ios/Podfile.lock
  client/ios/Supporting/Info.plist
  client/ios/twentyninek.xcodeproj/project.pbxproj
  client/package.json
  client/yarn.lock
Labels: native release

#1349 Update exercise “5b0dea9f-c665-41ce-a779-601d0cfa433d”
  content/src/exercises/5b0dea9f-c665-41ce-a779-601d0cfa433d.json
Labels: netlify-cms/pending_publish

#1364 Update exercise “3188a5ed-a1d6-451c-ae2a-f44f4df37495”
  content/src/exercises/3188a5ed-a1d6-451c-ae2a-f44f4df37495.json
Labels: netlify-cms/pending_publish

#1363 Update 📱 UI “Screen.Sessions”
  content/src/ui/Screen.Sessions.json
Labels: netlify-cms/pending_publish

#1360 🚢 Release 2.9.0
  client/android/app/build.gradle
  client/android/app/src/main/assets/modules.json
  client/ios/Podfile.lock
  client/ios/Supporting/Info.plist
  client/ios/twentyninek.xcodeproj/project.pbxproj
  client/package.json
  client/yarn.lock
Labels: native release
