Repository 29ki/29k, pull requests merged in 2023-01, with the labels that each got.

#1431 Update exercise “c5b1197a-4eec-4699-9dad-0e3d6323967b”
  content/src/exercises/c5b1197a-4eec-4699-9dad-0e3d6323967b.json
Labels: netlify-cms/pending_publish

#1434 Update 📱 UI “Component.SessionCard”
  content/src/ui/Component.SessionCard.json
Labels: netlify-cms/pending_publish

#1433 Update 📱 UI “Component.Interested”
  content/src/ui/Component.Interested.json
Labels: netlify-cms/pending_publish

#1437 Update 📱 UI “Modal.Contributors”
  content/src/ui/Modal.Contributors.json
Labels: netlify-cms/pending_publish

#1432 Update 📱 UI “Component.CheckPermissions”
  content/src/ui/Component.CheckPermissions.json
Labels: netlify-cms/pending_publish

#1438 Update 📱 UI “Modal.Partners”
  content/src/ui/Modal.Partners.json
Labels: netlify-cms/pending_publish

#1435 Update 📱 UI “Modal.ChangeLanguage”
  content/src/ui/Modal.ChangeLanguage.json
Labels: netlify-cms/pending_publish

#1441 Update 📱 UI “Screen.Profile”
  content/src/ui/Screen.Profile.json
Labels: netlify-cms/pending_publish

#1440 Update 📱 UI “Overlay.Community”
  content/src/ui/Overlay.Community.json
Labels: netlify-cms/pending_publish

#1442 Update 📱 UI “Screen.Sessions”
  content/src/ui/Screen.Sessions.json
Labels: netlify-cms/pending_publish

#1443 Update exercise “c5b1197a-4eec-4699-9dad-0e3d6323967b”
  content/src/exercises/c5b1197a-4eec-4699-9dad-0e3d6323967b.json
Labels: netlify-cms/pending_publish

#1444 Update exercise “c5b1197a-4eec-4699-9dad-0e3d6323967b”
  content/src/exercises/c5b1197a-4eec-4699-9dad-0e3d6323967b.json
Labels: netlify-cms/pending_publish

#1474 Update exercise “c5b1197a-4eec-4699-9dad-0e3d6323967b”
  content/src/exercises/c5b1197a-4eec-4699-9dad-0e3d6323967b.json
Labels: netlify-cms/pending_publish

#1398 🚢 Release 2.10.0
  client/android/app/build.gradle
  client/android/app/src/main/assets/modules.json
  client/ios/Podfile.lock
  client/ios/Supporting/Info.plist
  client/ios/twentyninek.xcodeproj/project.pbxproj
  client/package.json
  client/yarn.lock
Labels: native release

#1489 Update 📱 UI “Component.SessionReminder”
  content/src/ui/Component.SessionReminder.json
Labels: netlify-cms/pending_publish

#1494 Update exercise “3188a5ed-a1d6-451c-ae2a-f44f4df37495”
  content/src/exercises/3188a5ed-a1d6-451c-ae2a-f44f4df37495.json
Labels: netlify-cms/pending_publish

#1493 Enable backup of async storage
  client/android/app/src/main/AndroidManifest.xml
  client/ios/Supporting/Info.plist
Labels: native release

#1488 Update exercise “5b0dea9f-c665-41ce-a779-601d0cfa433d”
  content/src/exercises/5b0dea9f-c665-41ce-a779-601d0cfa433d.json
Labels: netlify-cms/pending_publish

#1502 Update exercise “185889ec-753b-4e2c-8322-3004013e8a6e”
  content/src/exercises/185889ec-753b-4e2c-8322-3004013e8a6e.json
Labels: netlify-cms/pending_publish

#1505 Update exercise “3188a5ed-a1d6-451c-ae2a-f44f4df37495”
  content/src/exercises/3188a5ed-a1d6-451c-ae2a-f44f4df37495.json
Labels: netlify-cms/pending_publish

#1539 Update exercise “c5b1197a-4eec-4699-9dad-0e3d6323967b”
  content/src/exercises/c5b1197a-4eec-4699-9dad-0e3d6323967b.json
Labels: netlify-cms/draft

#1536 Update exercise “5b0dea9f-c665-41ce-a779-601d0cfa433d”
  content/src/exercises/5b0dea9f-c665-41ce-a779-601d0cfa433d.json
Labels: netlify-cms/pending_publish

#1545 Update exercise “3188a5ed-a1d6-451c-ae2a-f44f4df37495”
  content/src/exercises/3188a5ed-a1d6-451c-ae2a-f44f4df37495.json
Labels: netlify-cms/pending_publish

#1546 Update exercise “3188a5ed-a1d6-451c-ae2a-f44f4df37495”
  content/src/exercises/3188a5ed-a1d6-451c-ae2a-f44f4df37495.json
Labels: netlify-cms/pending_publish

#1547 Update exercise “3188a5ed-a1d6-451c-ae2a-f44f4df37495”
  content/src/exercises/3188a5ed-a1d6-451c-ae2a-f44f4df37495.json
Labels: netlify-cms/pending_publish

#1557 Update exercise “c5b1197a-4eec-4699-9dad-0e3d6323967b”
  content/src/exercises/c5b1197a-4eec-4699-9dad-0e3d6323967b.json
Labels: netlify-cms/pending_publish

#1556 Update exercise “3188a5ed-a1d6-451c-ae2a-f44f4df37495”
  content/src/exercises/3188a5ed-a1d6-451c-ae2a-f44f4df37495.json
Labels: netlify-cms/pending_publish

#1565 Update exercise “3188a5ed-a1d6-451c-ae2a-f44f4df37495”
  content/src/exercises/3188a5ed-a1d6-451c-ae2a-f44f4df37495.json
Labels: netlify-cms/pending_publish

#1566 Update exercise “3188a5ed-a1d6-451c-ae2a-f44f4df37495”
  content/src/exercises/3188a5ed-a1d6-451c-ae2a-f44f4df37495.json
Labels: netlify-cms/pending_publish

#1567 Update exercise “3188a5ed-a1d6-451c-ae2a-f44f4df37495”
  content/src/exercises/3188a5ed-a1d6-451c-ae2a-f44f4df37495.json
Labels: netlify-cms/pending_publish

#1568 Update exercise “c5b1197a-4eec-4699-9dad-0e3d6323967b”
  content/src/exercises/c5b1197a-4eec-4699-9dad-0e3d6323967b.json
Labels: netlify-cms/pending_publish

#1570 Update exercise “3188a5ed-a1d6-451c-ae2a-f44f4df37495”
  content/src/exercises/3188a5ed-a1d6-451c-ae2a-f44f4df37495.json
Labels: netlify-cms/pending_publish

#1569 Update exercise “c5b1197a-4eec-4699-9dad-0e3d6323967b”
  content/src/exercises/c5b1197a-4eec-4699-9dad-0e3d6323967b.json
Labels: netlify-cms/pending_publish

#1535 🚢 Release 2.12.0
  client/__mocks__/zustand.ts
  client/android/app/build.gradle
  client/android/app/src/main/assets/modules.json
  client/ios/Podfile.lock
  client/ios/Supporting/Info.plist
  client/ios/twentyninek.xcodeproj/project.pbxproj
  client/package.json
  client/src/lib/appState/state/state.ts
  client/src/lib/codePush/state/state.ts
  client/src/lib/daily/state/state.ts
  client/src/lib/killSwitch/state/state.ts
  client/src/lib/navigation/state/state.ts
  client/src/lib/notifications/state/state.ts
  client/src/lib/sessions/state/state.ts
  client/src/lib/user/state/state.ts
  client/src/routes/Session/state/sessionNotificationsState.ts
  client/src/routes/Session/state/state.ts
  client/yarn.lock
  functions/src/api/killswitch/index.spec.ts
  functions/src/api/killswitch/index.ts
Labels: native release

#1593 Update exercise “3188a5ed-a1d6-451c-ae2a-f44f4df37495”
  content/src/exercises/3188a5ed-a1d6-451c-ae2a-f44f4df37495.json
Labels: netlify-cms/pending_publish

#1600 Update exercise “c5b1197a-4eec-4699-9dad-0e3d6323967b”
  content/src/exercises/c5b1197a-4eec-4699-9dad-0e3d6323967b.json
Labels: netlify-cms/pending_publish

#1599 Update exercise “095f9642-73b6-4c9a-ae9a-ea7dea7363f5”
  content/src/exercises/095f9642-73b6-4c9a-ae9a-ea7dea7363f5.json
Labels: netlify-cms/pending_publish

#1596 Update exercise “185889ec-753b-4e2c-8322-3004013e8a6e”
  content/src/exercises/185889ec-753b-4e2c-8322-3004013e8a6e.json
Labels: netlify-cms/pending_publish

#1598 Update exercise “5b0dea9f-c665-41ce-a779-601d0cfa433d”
  content/src/exercises/5b0dea9f-c665-41ce-a779-601d0cfa433d.json
Labels: netlify-cms/pending_publish

#1597 Update exercise “ea0b48c1-745e-418d-93e7-2d8a6cd72898”
  content/src/exercises/ea0b48c1-745e-418d-93e7-2d8a6cd72898.json
Labels: netlify-cms/pending_publish

#1602 Update exercise “c5b1197a-4eec-4699-9dad-0e3d6323967b”
  content/src/exercises/c5b1197a-4eec-4699-9dad-0e3d6323967b.json
Labels: netlify-cms/pending_publish

#1603 Update exercise “94575e97-fe03-4bfd-94a6-50aaf721d47e”
  content/src/exercises/94575e97-fe03-4bfd-94a6-50aaf721d47e.json
Labels: netlify-cms/pending_publish

#1604 Update exercise “3188a5ed-a1d6-451c-ae2a-f44f4df37495”
  content/src/exercises/3188a5ed-a1d6-451c-ae2a-f44f4df37495.json
Labels: netlify-cms/pending_publish

#1605 Update exercise “185889ec-753b-4e2c-8322-3004013e8a6e”
  content/src/exercises/185889ec-753b-4e2c-8322-3004013e8a6e.json
Labels: netlify-cms/pending_publish

#1606 Update exercise “095f9642-73b6-4c9a-ae9a-ea7dea7363f5”
  content/src/exercises/095f9642-73b6-4c9a-ae9a-ea7dea7363f5.json
Labels: netlify-cms/pending_publish

#1611 Remove react-native-swipe-gestures
  client/package.json
  client/yarn.lock
Labels: native release

#1613 Create exercise “9ac0c561-ff26-45fc-b6d5-0a983432394e”
  content/src/exercises/9ac0c561-ff26-45fc-b6d5-0a983432394e.json
Labels: netlify-cms/pending_publish

#1615 Update exercise “9ac0c561-ff26-45fc-b6d5-0a983432394e”
  content/src/exercises/9ac0c561-ff26-45fc-b6d5-0a983432394e.json
Labels: netlify-cms/pending_publish

#1614 Update ⚙️ Settings “exercise-defaults”
  cms/src/defaults/exercise.json
  cms/src/fields/exercise.ts
Labels: netlify-cms/pending_publish

#1619 Create exercise “b18c1cff-bb43-44b1-81a1-2877cc018ab4”
  content/src/exercises/b18c1cff-bb43-44b1-81a1-2877cc018ab4.json
Labels: netlify-cms/pending_publish

#1625 Update exercise “3188a5ed-a1d6-451c-ae2a-f44f4df37495”
  content/src/exercises/3188a5ed-a1d6-451c-ae2a-f44f4df37495.json
Labels: netlify-cms/pending_publish

#1571 🚢 Release 2.13.0
  client/android/app/build.gradle
  client/android/app/src/main/assets/modules.json
  client/ios/Podfile.lock
  client/ios/Supporting/Info.plist
  client/ios/twentyninek.xcodeproj/project.pbxproj
  client/package.json
  client/src/routes/Session/ChangingRoom.tsx
  client/src/routes/Session/components/Participants/AudioIndicator.tsx
  client/src/routes/Session/components/Participants/Participant.tsx
  client/src/routes/Session/components/Participants/VideoOffIndicator.tsx
  client/src/routes/Session/components/Session.library.tsx
  client/src/routes/Session/hooks/useCheckPermissions.ts
  client/yarn.lock
  shared/src/constants/colors.ts
Labels: native release

#1626 Update exercise “c5b1197a-4eec-4699-9dad-0e3d6323967b”
  content/src/exercises/c5b1197a-4eec-4699-9dad-0e3d6323967b.json
Labels: netlify-cms/pending_publish

#1636 Backend metrics adaptor in client (metrics part 3)
  .github/workflows/build-android.yml
  .github/workflows/build-ios.yml
  .github/workflows/deploy-codepush.yml
  client/.env.example
  client/__mocks__/@react-native-firebase/auth.js
  client/ios/Podfile.lock
  client/jest.config.js
  client/package.json
  client/src/Bootstrap.tsx
  client/src/lib/apiClient/apiClient.spec.ts
  client/src/lib/apiClient/apiClient.ts
  client/src/lib/metrics/adaptors/backEnd/hooks/useNavigationTracker.ts
  client/src/lib/metrics/adaptors/backEnd/index.spec.ts
  client/src/lib/metrics/adaptors/backEnd/index.tsx
  client/src/lib/metrics/adaptors/backEnd/utils/getMetricsUid.spec.ts
  client/src/lib/metrics/adaptors/backEnd/utils/getMetricsUid.ts
  client/src/lib/metrics/adaptors/backEnd/utils/metricsClient.spec.ts
  client/src/lib/metrics/adaptors/backEnd/utils/metricsClient.ts
  client/src/lib/metrics/adaptors/postHog/index.spec.ts
  client/src/lib/metrics/adaptors/postHog/index.tsx
  client/src/lib/metrics/index.spec.ts
  client/src/lib/metrics/index.tsx
  client/src/lib/metrics/types/Adaptor.ts
  client/src/lib/metrics/types/Events.ts
  client/src/lib/metrics/types/Properties.ts
  client/src/lib/user/hooks/useChangeProfilePicture.ts
  client/src/lib/user/hooks/useCurrentUserState.ts
  client/src/lib/user/hooks/useUpdateProfileDetails.spec.ts
  client/src/lib/user/hooks/useUpdateProfileDetails.ts
  client/src/lib/user/index.spec.ts
  client/src/lib/user/index.ts
  client/src/lib/user/state/state.ts
  client/src/lib/utils/string.spec.ts
  client/src/lib/utils/string.ts
  client/types/env.d.ts
  client/yarn.lock
  docs/INSTALLATION.md
Labels: native release
