Repository 29ki/29k, pull requests merged in 2023-02, with the labels that each got.

#1610 Update exercise “5b0dea9f-c665-41ce-a779-601d0cfa433d”
  content/src/exercises/5b0dea9f-c665-41ce-a779-601d0cfa433d.json
Labels: netlify-cms/pending_publish

#1676 Update exercise “3188a5ed-a1d6-451c-ae2a-f44f4df37495”
  content/src/exercises/3188a5ed-a1d6-451c-ae2a-f44f4df37495.json
Labels: netlify-cms/pending_publish

#1679 Update exercise “9ac0c561-ff26-45fc-b6d5-0a983432394e”
  content/src/exercises/9ac0c561-ff26-45fc-b6d5-0a983432394e.json
Labels: netlify-cms/pending_publish

#1677 Update exercise “095f9642-73b6-4c9a-ae9a-ea7dea7363f5”
  content/src/exercises/095f9642-73b6-4c9a-ae9a-ea7dea7363f5.json
Labels: netlify-cms/pending_publish

#1675 Update exercise “ea0b48c1-745e-418d-93e7-2d8a6cd72898”
  content/src/exercises/ea0b48c1-745e-418d-93e7-2d8a6cd72898.json
Labels: netlify-cms/pending_publish

#1673 Update exercise “185889ec-753b-4e2c-8322-3004013e8a6e”
  content/src/exercises/185889ec-753b-4e2c-8322-3004013e8a6e.json
Labels: netlify-cms/pending_publish

#1672 Update exercise “94575e97-fe03-4bfd-94a6-50aaf721d47e”
  content/src/exercises/94575e97-fe03-4bfd-94a6-50aaf721d47e.json
Labels: netlify-cms/pending_publish

#1674 Update exercise “b18c1cff-bb43-44b1-81a1-2877cc018ab4”
  content/src/exercises/b18c1cff-bb43-44b1-81a1-2877cc018ab4.json
Labels: netlify-cms/pending_publish

#1678 Update exercise “c5b1197a-4eec-4699-9dad-0e3d6323967b”
  content/src/exercises/c5b1197a-4eec-4699-9dad-0e3d6323967b.json
Labels: netlify-cms/pending_publish

#1637 🚢 Release 2.14.0
  .github/workflows/build-android.yml
  .github/workflows/build-ios.yml
  .github/workflows/deploy-codepush.yml
  client/.env.example
  client/android/app/build.gradle
  client/android/app/src/main/assets/modules.json
  client/ios/Podfile.lock
  client/ios/Supporting/Info.plist
  client/ios/twentyninek.xcodeproj/project.pbxproj
  client/jest.config.js
  client/package.json
  client/src/Bootstrap.tsx
  client/src/lib/metrics/adaptors/backEnd/hooks/useNavigationTracker.ts
  client/src/lib/metrics/adaptors/backEnd/index.spec.ts
  client/src/lib/metrics/adaptors/backEnd/index.tsx
  client/src/lib/metrics/adaptors/backEnd/utils/getMetricsUid.spec.ts
  client/src/lib/metrics/adaptors/backEnd/utils/getMetricsUid.ts
  client/src/lib/metrics/adaptors/backEnd/utils/metricsClient.spec.ts
  client/src/lib/metrics/adaptors/backEnd/utils/metricsClient.ts
  client/src/lib/metrics/adaptors/postHog/index.spec.ts
  client/src/lib/metrics/adaptors/postHog/index.tsx
  client/src/lib/metrics/index.spec.ts
  client/src/lib/metrics/index.tsx
  client/src/lib/metrics/types/Adaptor.ts
  client/src/lib/metrics/types/Events.ts
  client/src/lib/metrics/types/Properties.ts
  client/types/env.d.ts
  client/yarn.lock
  docs/INSTALLATION.md
Labels: native release

#1690 Create exercise “41ba136c-4950-42fc-bd6b-761b829ee371”
  content/src/exercises/41ba136c-4950-42fc-bd6b-761b829ee371.json
Labels: netlify-cms/pending_publish

#1696 Update exercise “ea0b48c1-745e-418d-93e7-2d8a6cd72898”
  content/src/exercises/ea0b48c1-745e-418d-93e7-2d8a6cd72898.json
Labels: netlify-cms/pending_publish

#1697 Update exercise “095f9642-73b6-4c9a-ae9a-ea7dea7363f5”
  content/src/exercises/095f9642-73b6-4c9a-ae9a-ea7dea7363f5.json
Labels: netlify-cms/pending_publish

#1699 Update exercise “095f9642-73b6-4c9a-ae9a-ea7dea7363f5”
  content/src/exercises/095f9642-73b6-4c9a-ae9a-ea7dea7363f5.json
Labels: netlify-cms/pending_publish

#1701 Update exercise “095f9642-73b6-4c9a-ae9a-ea7dea7363f5”
  content/src/exercises/095f9642-73b6-4c9a-ae9a-ea7dea7363f5.json
Labels: netlify-cms/pending_publish

#1704 Update exercise “5b0dea9f-c665-41ce-a779-601d0cfa433d”
  content/src/exercises/5b0dea9f-c665-41ce-a779-601d0cfa433d.json
Labels: netlify-cms/pending_publish

#1707 Remove duplicate UUID packages
  client/package.json
  client/src/lib/metrics/adaptors/backEnd/utils/getMetricsUid.spec.ts
  client/src/lib/metrics/adaptors/backEnd/utils/getMetricsUid.ts
  client/src/lib/utils/id.ts
  client/yarn.lock
Labels: native release

#1694 Update exercise “c5b1197a-4eec-4699-9dad-0e3d6323967b”
  content/src/exercises/c5b1197a-4eec-4699-9dad-0e3d6323967b.json
Labels: netlify-cms/pending_publish

#1744 Update 📱 UI “Modal.CreateSession”
  content/src/ui/Modal.CreateSession.json
Labels: netlify-cms/pending_publish

#1743 Update 📱 UI “Component.EditSessionType”
  content/src/ui/Component.EditSessionType.json
Labels: netlify-cms/pending_publish

#1742 Update 📱 UI “Modal.Session”
  content/src/ui/Modal.Session.json
Labels: netlify-cms/pending_publish

#1750 Bump kill switch to 2.15.1
  functions/src/api/killswitch/index.spec.ts
  functions/src/api/killswitch/index.ts
Labels: native release

#1752 Update exercise “c5b1197a-4eec-4699-9dad-0e3d6323967b”
  content/src/exercises/c5b1197a-4eec-4699-9dad-0e3d6323967b.json
Labels: netlify-cms/pending_publish

#1745 🚢 Release 2.15.1
  client/android/app/build.gradle
  client/android/app/src/main/assets/modules.json
  client/ios/Podfile.lock
  client/ios/Supporting/Info.plist
  client/ios/twentyninek.xcodeproj/project.pbxproj
  client/package.json
  client/src/lib/components/Cards/SessionCard/SessionCard.tsx
  client/src/lib/metrics/adaptors/backEnd/utils/getMetricsUid.spec.ts
  client/src/lib/metrics/adaptors/backEnd/utils/getMetricsUid.ts
  client/src/lib/session/hooks/useAsyncSessionMetricEvents.spec.ts
  client/src/lib/session/hooks/useAsyncSessionMetricEvents.ts
  client/src/lib/session/hooks/useExerciseTheme.spec.ts
  client/src/lib/session/hooks/useLeaveSession.spec.ts
  client/src/lib/session/hooks/useLeaveSession.ts
  client/src/lib/session/hooks/useLiveSessionMetricEvents.spec.ts
  client/src/lib/session/hooks/useLiveSessionMetricEvents.ts
  client/src/lib/session/hooks/useSessionExercise.spec.ts
  client/src/lib/session/hooks/useSessionExercise.ts
  client/src/lib/session/hooks/useSessionSlideState.spec.ts
  client/src/lib/session/hooks/useStartAsyncSession.ts
  client/src/lib/sessions/api/session.ts
  client/src/lib/sessions/hooks/useLogAsyncSessionMetricEvents.ts
  client/src/lib/sessions/hooks/useLogSessionMetricEvents.spec.ts
  client/src/lib/sessions/hooks/useLogSessionMetricEvents.ts
  client/src/lib/sessions/hooks/useSessionNotificationReminder.spec.ts
  client/src/lib/sessions/hooks/useSessionNotificationReminder.ts
  client/src/lib/sessions/hooks/useSessions.spec.ts
  client/src/lib/sessions/hooks/useSessions.ts
  client/src/lib/user/state/migration/__mocks__/v0.ts
  client/src/lib/user/state/migration/index.spec.ts
  client/src/lib/user/state/migration/index.ts
  client/src/lib/user/state/migration/v0.spec.ts
  client/src/lib/user/state/migration/v0.ts
  client/src/lib/user/state/migration/v1.spec.ts
  client/src/lib/user/state/migration/v1.ts
  client/src/lib/user/state/state.ts
  client/src/lib/utils/id.ts
  client/src/routes/AsyncSession/IntroPortal.tsx
  client/src/routes/AsyncSession/OutroPortal.tsx
  client/src/routes/AsyncSession/Session.tsx
  client/src/routes/AsyncSessionModal/AsyncSessionModal.tsx
  client/src/routes/CreateSessionModal/components/steps/SetDateTimeStep.tsx
  client/src/routes/LiveSession/OutroPortal.tsx
  client/src/routes/LiveSession/Session.tsx
  client/src/routes/SessionModal/SessionModal.tsx
  client/yarn.lock
  functions/scripts/migrateSessionContentIdToExerciseId.ts
  functions/scripts/migrateSessionStates.ts
  functions/src/api/killswitch/index.spec.ts
  functions/src/api/killswitch/index.ts
  functions/src/api/sessions/index.spec.ts
  functions/src/api/sessions/index.ts
  functions/src/controllers/sessions.spec.ts
  functions/src/controllers/sessions.ts
  functions/src/models/session.spec.ts
  functions/src/models/session.ts
  shared/src/types/Session.ts
Labels: native release

#1753 Update exercise “5b0dea9f-c665-41ce-a779-601d0cfa433d”
  content/src/exercises/5b0dea9f-c665-41ce-a779-601d0cfa433d.json
Labels: netlify-cms/pending_publish

#1758 Update exercise “3188a5ed-a1d6-451c-ae2a-f44f4df37495”
  content/src/exercises/3188a5ed-a1d6-451c-ae2a-f44f4df37495.json
Labels: netlify-cms/pending_publish

#1762 Update 📱 UI “Component.HostNotes”
  content/src/ui/Component.HostNotes.json
Labels: netlify-cms/pending_publish

#1766 Update exercise “94575e97-fe03-4bfd-94a6-50aaf721d47e”
  content/src/exercises/94575e97-fe03-4bfd-94a6-50aaf721d47e.json
Labels: netlify-cms/pending_publish

#1768 Update exercise “095f9642-73b6-4c9a-ae9a-ea7dea7363f5”
  content/src/exercises/095f9642-73b6-4c9a-ae9a-ea7dea7363f5.json
Labels: netlify-cms/pending_publish

#1770 Update exercise “095f9642-73b6-4c9a-ae9a-ea7dea7363f5”
  content/src/exercises/095f9642-73b6-4c9a-ae9a-ea7dea7363f5.json
Labels: netlify-cms/pending_publish

#1771 Update exercise “095f9642-73b6-4c9a-ae9a-ea7dea7363f5”
  content/src/exercises/095f9642-73b6-4c9a-ae9a-ea7dea7363f5.json
Labels: netlify-cms/pending_publish

#1772 Update exercise “94575e97-fe03-4bfd-94a6-50aaf721d47e”
  content/src/exercises/94575e97-fe03-4bfd-94a6-50aaf721d47e.json
Labels: netlify-cms/pending_publish

#1778 Update exercise “5b0dea9f-c665-41ce-a779-601d0cfa433d”
  content/src/exercises/5b0dea9f-c665-41ce-a779-601d0cfa433d.json
Labels: netlify-cms/pending_publish

#1779 Update exercise “185889ec-753b-4e2c-8322-3004013e8a6e”
  content/src/exercises/185889ec-753b-4e2c-8322-3004013e8a6e.json
Labels: netlify-cms/pending_publish

#1829 Update 📱 UI “Component.ConfirmSessionReminder”
  content/src/ui/Component.ConfirmSessionReminder.json
Labels: netlify-cms/pending_publish

#1830 Remove unecessary completed session sorting on Joruney
  client/src/routes/Journey/Journey.tsx
Labels: bug

#1834 Update exercise “095f9642-73b6-4c9a-ae9a-ea7dea7363f5”
  content/src/exercises/095f9642-73b6-4c9a-ae9a-ea7dea7363f5.json
Labels: netlify-cms/pending_publish

#1835 Update exercise “3188a5ed-a1d6-451c-ae2a-f44f4df37495”
  content/src/exercises/3188a5ed-a1d6-451c-ae2a-f44f4df37495.json
Labels: netlify-cms/pending_publish

#1836 Update 📱 UI “Component.Tabs”
  content/src/ui/Component.Tabs.json
Labels: netlify-cms/pending_publish

#1837 Update 📱 UI “Screen.Journey”
  content/src/ui/Screen.Journey.json
Labels: netlify-cms/pending_publish

#1838 Update 📱 UI “Modal.CreateSession”
  content/src/ui/Modal.CreateSession.json
Labels: netlify-cms/pending_publish

#1855 Update 📱 UI “Screen.Profile”
  content/src/ui/Screen.Profile.json
Labels: netlify-cms/pending_publish

#1856 Update 📱 UI “Screen.Sessions”
  content/src/ui/Screen.Sessions.json
Labels: netlify-cms/pending_publish

#1849 Update 📱 UI “Modal.Contact”
  content/src/ui/Modal.Contact.json
Labels: netlify-cms/pending_publish

#1840 Update 📱 UI “Component.CompletedSessionCard”
  content/src/ui/Component.CompletedSessionCard.json
Labels: netlify-cms/pending_publish

#1847 Update 📱 UI “Modal.CompletedSession”
  content/src/ui/Modal.CompletedSession.json
Labels: netlify-cms/pending_publish

#1851 Update 📱 UI “Modal.UpgradeAccount”
  content/src/ui/Modal.UpgradeAccount.json
Labels: netlify-cms/pending_publish

#1844 Update 📱 UI “Component.HostNotes”
  content/src/ui/Component.HostNotes.json
Labels: netlify-cms/pending_publish

#1842 Update 📱 UI “Component.ConfirmSessionReminder”
  content/src/ui/Component.ConfirmSessionReminder.json
Labels: netlify-cms/pending_publish

#1852 Update 📱 UI “Overlay.About”
  content/src/ui/Overlay.About.json
Labels: netlify-cms/pending_publish

#1854 Update 📱 UI “Screen.Journey”
  content/src/ui/Screen.Journey.json
Labels: netlify-cms/pending_publish

#1843 Update 📱 UI “Component.CrashErrorMessage”
  content/src/ui/Component.CrashErrorMessage.json
Labels: netlify-cms/pending_publish

#1845 Update 📱 UI “Component.RequestNotificationPermission”
  content/src/ui/Component.RequestNotificationPermission.json
Labels: netlify-cms/pending_publish

#1860 Update 📱 UI “Screen.Profile”
  content/src/ui/Screen.Profile.json
Labels: netlify-cms/pending_publish

#1862 Update exercise “94575e97-fe03-4bfd-94a6-50aaf721d47e”
  content/src/exercises/94575e97-fe03-4bfd-94a6-50aaf721d47e.json
Labels: netlify-cms/pending_publish

#1863 Update exercise “ea0b48c1-745e-418d-93e7-2d8a6cd72898”
  content/src/exercises/ea0b48c1-745e-418d-93e7-2d8a6cd72898.json
Labels: netlify-cms/pending_publish

#1861 Update 📱 UI “Screen.Sessions”
  content/src/ui/Screen.Sessions.json
Labels: netlify-cms/pending_publish

#1864 Update 📱 UI “Screen.Profile”
  content/src/ui/Screen.Profile.json
Labels: netlify-cms/pending_publish

#1827 Release 2.15.2
  client/android/app/build.gradle
  client/android/app/src/main/assets/modules.json
  client/ios/Podfile.lock
  client/ios/Supporting/Info.plist
  client/ios/twentyninek.xcodeproj/project.pbxproj
  client/package.json
  client/yarn.lock
Labels: native release

#1866 Update exercise “5b0dea9f-c665-41ce-a779-601d0cfa433d”
  content/src/exercises/5b0dea9f-c665-41ce-a779-601d0cfa433d.json
Labels: netlify-cms/pending_publish

#1870 Update exercise “185889ec-753b-4e2c-8322-3004013e8a6e”
  content/src/exercises/185889ec-753b-4e2c-8322-3004013e8a6e.json
Labels: netlify-cms/pending_publish

#1869 Update exercise “095f9642-73b6-4c9a-ae9a-ea7dea7363f5”
  content/src/exercises/095f9642-73b6-4c9a-ae9a-ea7dea7363f5.json
Labels: netlify-cms/pending_publish

#1868 Update exercise “c5b1197a-4eec-4699-9dad-0e3d6323967b”
  content/src/exercises/c5b1197a-4eec-4699-9dad-0e3d6323967b.json
Labels: netlify-cms/pending_publish

#1873 Update exercise “ea0b48c1-745e-418d-93e7-2d8a6cd72898”
  content/src/exercises/ea0b48c1-745e-418d-93e7-2d8a6cd72898.json
Labels: netlify-cms/pending_publish

#1871 Update exercise “3188a5ed-a1d6-451c-ae2a-f44f4df37495”
  content/src/exercises/3188a5ed-a1d6-451c-ae2a-f44f4df37495.json
Labels: netlify-cms/pending_publish

#1879 Update exercise “9ac0c561-ff26-45fc-b6d5-0a983432394e”
  content/src/exercises/9ac0c561-ff26-45fc-b6d5-0a983432394e.json
Labels: netlify-cms/pending_publish

#1880 Update exercise “9ac0c561-ff26-45fc-b6d5-0a983432394e”
  content/src/exercises/9ac0c561-ff26-45fc-b6d5-0a983432394e.json
Labels: netlify-cms/pending_publish

#1881 Update exercise “095f9642-73b6-4c9a-ae9a-ea7dea7363f5”
  content/src/exercises/095f9642-73b6-4c9a-ae9a-ea7dea7363f5.json
Labels: netlify-cms/pending_publish

#1882 Update exercise “94575e97-fe03-4bfd-94a6-50aaf721d47e”
  content/src/exercises/94575e97-fe03-4bfd-94a6-50aaf721d47e.json
Labels: netlify-cms/pending_publish

#1916 Update 📱 UI “Component.Sharing”
  content/src/ui/Component.Sharing.json
Labels: netlify-cms/pending_publish

#1917 Update 📱 UI “Component.MyPostCard”
  content/src/ui/Component.MyPostCard.json
Labels: netlify-cms/pending_publish

#1918 Update 📱 UI “Modal.Sharing”
  content/src/ui/Modal.Sharing.json
Labels: netlify-cms/pending_publish

#1928 Update exercise “9ac0c561-ff26-45fc-b6d5-0a983432394e”
  content/src/exercises/9ac0c561-ff26-45fc-b6d5-0a983432394e.json
Labels: netlify-cms/pending_publish

#1929 Update exercise “9ac0c561-ff26-45fc-b6d5-0a983432394e”
  content/src/exercises/9ac0c561-ff26-45fc-b6d5-0a983432394e.json
Labels: netlify-cms/pending_publish

#1932 Update exercise “9ac0c561-ff26-45fc-b6d5-0a983432394e”
  content/src/exercises/9ac0c561-ff26-45fc-b6d5-0a983432394e.json
Labels: netlify-cms/pending_publish

#1933 Update exercise “9ac0c561-ff26-45fc-b6d5-0a983432394e”
  content/src/exercises/9ac0c561-ff26-45fc-b6d5-0a983432394e.json
Labels: netlify-cms/pending_publish

#1942 Update 📱 UI “Modal.CreateSession”
  content/src/ui/Modal.CreateSession.json
Labels: netlify-cms/pending_publish

#1943 Update 📱 UI “Overlay.About”
  content/src/ui/Overlay.About.json
Labels: netlify-cms/pending_publish

#1945 Update 📱 UI “Screen.Welcome”
  content/src/ui/Screen.Welcome.json
Labels: netlify-cms/pending_publish

#1946 Update exercise “3188a5ed-a1d6-451c-ae2a-f44f4df37495”
  content/src/exercises/3188a5ed-a1d6-451c-ae2a-f44f4df37495.json
Labels: netlify-cms/pending_publish

#1948 Update 📱 UI “Overlay.AboutEditorial”
  content/src/ui/Overlay.AboutEditorial.json
Labels: netlify-cms/pending_publish

#1949 Update 📱 UI “Screen.Welcome”
  content/src/ui/Screen.Welcome.json
Labels: netlify-cms/pending_publish

#1952 Update 📱 UI “Component.Tabs”
  content/src/ui/Component.Tabs.json
Labels: netlify-cms/pending_publish

#1953 Update 📱 UI “Modal.CreateSession”
  content/src/ui/Modal.CreateSession.json
Labels: netlify-cms/pending_publish

#1983 Update exercise “9ac0c561-ff26-45fc-b6d5-0a983432394e”
  content/src/exercises/9ac0c561-ff26-45fc-b6d5-0a983432394e.json
Labels: netlify-cms/pending_publish
