Repository 29ki/29k, pull requests merged in 2023-08, with the labels that each got.

#3383 Migrate from ExoPlayer2 to Media3
  client/android/app/build.gradle
  client/android/app/src/main/java/org/twentyninek/app/cupcake/newarchitecture/videoLooper/MediaItemConfig.java
  client/android/app/src/main/java/org/twentyninek/app/cupcake/newarchitecture/videoLooper/ReactVideoLooperView.java
  client/android/app/src/main/java/org/twentyninek/app/cupcake/newarchitecture/videoLooper/VideoCacheManager.java
Labels: native release

#3386 Adjust volume on android
  client/__mocks__/react-native-volume-manager.js
  client/ios/Podfile.lock
  client/package.json
  client/src/lib/session/components/Slides/Slides/Content.tsx
  client/src/lib/session/hooks/useAdjustVolume.spec.ts
  client/src/lib/session/hooks/useAdjustVolume.ts
  client/yarn.lock
Labels: native release

#3180 🚢 Release 2.32.0
  client/__mocks__/react-native-volume-manager.js
  client/android/app/build.gradle
  client/android/app/src/main/java/org/twentyninek/app/cupcake/newarchitecture/videoLooper/MediaItemConfig.java
  client/android/app/src/main/java/org/twentyninek/app/cupcake/newarchitecture/videoLooper/ReactVideoLooperView.java
  client/android/app/src/main/java/org/twentyninek/app/cupcake/newarchitecture/videoLooper/VideoCacheManager.java
  client/ios/Podfile.lock
  client/ios/Supporting/Info.plist
  client/ios/twentyninek.xcodeproj/project.pbxproj
  client/package.json
  client/src/lib/components/Icons/AnimatedIcon.tsx
  client/src/lib/components/LottiePlayer/LottiePlayer.tsx
  client/src/lib/components/LottiePlayer/hooks/useFetchLottie.ts
  client/src/lib/session/components/Slides/Slides/Content.tsx
  client/src/lib/session/hooks/useAdjustVolume.spec.ts
  client/src/lib/session/hooks/useAdjustVolume.ts
  client/yarn.lock
Labels: native release

#3435 Update exercise “095f9642-73b6-4c9a-ae9a-ea7dea7363f5”
  content/src/exercises/095f9642-73b6-4c9a-ae9a-ea7dea7363f5.json
Labels: netlify-cms/pending_publish

#3436 Update exercise “61adeaf2-70ab-4c6c-854c-2c16f762a3c5”
  content/src/exercises/61adeaf2-70ab-4c6c-854c-2c16f762a3c5.json
Labels: netlify-cms/pending_publish

#3434 Update exercise “640e4d9f-bb88-44af-a032-116a82f080f6”
  content/src/exercises/640e4d9f-bb88-44af-a032-116a82f080f6.json
Labels: netlify-cms/pending_publish

#3442 Update exercise “0bcb6eb0-fdfe-466d-8603-ae6de15fcbc5”
  content/src/exercises/0bcb6eb0-fdfe-466d-8603-ae6de15fcbc5.json
Labels: netlify-cms/pending_publish

#3426 🚢 Release 2.32.1
  client/android/app/build.gradle
  client/ios/Podfile.lock
  client/ios/Supporting/Info.plist
  client/ios/twentyninek.xcodeproj/project.pbxproj
  client/package.json
  client/yarn.lock
Labels: native release

#3446 Update collection “af1c4ac9-1bae-4cb1-8c98-e1f98a8aea66”
  content/src/collections/af1c4ac9-1bae-4cb1-8c98-e1f98a8aea66.json
Labels: netlify-cms/pending_publish

#3445 Update collection “8cb72f0d-3aad-4fe6-bf08-560b108bb439”
  content/src/collections/8cb72f0d-3aad-4fe6-bf08-560b108bb439.json
Labels: netlify-cms/pending_publish

#3448 Update 📱 UI “Component.AppVersion”
  content/src/ui/Component.AppVersion.json
Labels: netlify-cms/pending_publish

#3443 Update collection “68172f5c-955a-43e0-9cef-ae3bc77c9593”
  content/src/collections/68172f5c-955a-43e0-9cef-ae3bc77c9593.json
Labels: netlify-cms/pending_publish

#3453 Update 📱 UI “Component.Tabs”
  content/src/ui/Component.Tabs.json
Labels: netlify-cms/pending_publish

#3447 Update collection “46f653cd-b77f-458d-a257-1b171591c08b”
  content/src/collections/46f653cd-b77f-458d-a257-1b171591c08b.json
Labels: netlify-cms/pending_publish

#3451 Update 📱 UI “Component.Counter”
  content/src/ui/Component.Counter.json
Labels: netlify-cms/pending_publish

#3450 Update 📱 UI “Component.ConfirmPracticeReminders”
  content/src/ui/Component.ConfirmPracticeReminders.json
Labels: netlify-cms/pending_publish

#3444 Update collection “716c2b31-612c-40c4-8e85-90f0a2af380e”
  content/src/collections/716c2b31-612c-40c4-8e85-90f0a2af380e.json
Labels: netlify-cms/pending_publish

#3449 Update 📱 UI “Component.Card”
  content/src/ui/Component.Card.json
Labels: netlify-cms/pending_publish

#3452 Update 📱 UI “Component.SessionCard”
  content/src/ui/Component.SessionCard.json
Labels: netlify-cms/pending_publish

#3454 Update 📱 UI “Modal.CalmDown”
  content/src/ui/Modal.CalmDown.json
Labels: netlify-cms/pending_publish

#3457 Create collection “d9897547-18a2-4404-b12b-324458021783”
  content/src/collections/d9897547-18a2-4404-b12b-324458021783.json
Labels: netlify-cms/pending_publish

#3456 Update exercise “0bcb6eb0-fdfe-466d-8603-ae6de15fcbc5”
  content/src/exercises/0bcb6eb0-fdfe-466d-8603-ae6de15fcbc5.json
Labels: netlify-cms/pending_publish

#3459 Update exercise “61adeaf2-70ab-4c6c-854c-2c16f762a3c5”
  content/src/exercises/61adeaf2-70ab-4c6c-854c-2c16f762a3c5.json
Labels: netlify-cms/pending_publish

#3461 Update exercise “61adeaf2-70ab-4c6c-854c-2c16f762a3c5”
  content/src/exercises/61adeaf2-70ab-4c6c-854c-2c16f762a3c5.json
Labels: netlify-cms/pending_publish

#3467 Update exercise “640e4d9f-bb88-44af-a032-116a82f080f6”
  content/src/exercises/640e4d9f-bb88-44af-a032-116a82f080f6.json
Labels: netlify-cms/pending_publish

#3468 Update exercise “61adeaf2-70ab-4c6c-854c-2c16f762a3c5”
  content/src/exercises/61adeaf2-70ab-4c6c-854c-2c16f762a3c5.json
Labels: netlify-cms/pending_publish

#3469 Update exercise “0bcb6eb0-fdfe-466d-8603-ae6de15fcbc5”
  content/src/exercises/0bcb6eb0-fdfe-466d-8603-ae6de15fcbc5.json
Labels: netlify-cms/pending_publish

#3470 Update exercise “961656ea-021c-4faa-ae03-46d6ace4be4b”
  content/src/exercises/961656ea-021c-4faa-ae03-46d6ace4be4b.json
Labels: netlify-cms/pending_publish

#3472 Update exercise “640e4d9f-bb88-44af-a032-116a82f080f6”
  content/src/exercises/640e4d9f-bb88-44af-a032-116a82f080f6.json
Labels: netlify-cms/pending_publish

#3474 Update collection “46f653cd-b77f-458d-a257-1b171591c08b”
  content/src/collections/46f653cd-b77f-458d-a257-1b171591c08b.json
Labels: netlify-cms/pending_publish

#3475 Update exercise “640e4d9f-bb88-44af-a032-116a82f080f6”
  content/src/exercises/640e4d9f-bb88-44af-a032-116a82f080f6.json
Labels: netlify-cms/pending_publish

#3476 Update exercise “961656ea-021c-4faa-ae03-46d6ace4be4b”
  content/src/exercises/961656ea-021c-4faa-ae03-46d6ace4be4b.json
Labels: netlify-cms/pending_publish

#3477 Update exercise “640e4d9f-bb88-44af-a032-116a82f080f6”
  content/src/exercises/640e4d9f-bb88-44af-a032-116a82f080f6.json
Labels: netlify-cms/pending_publish

#3478 Update exercise “61adeaf2-70ab-4c6c-854c-2c16f762a3c5”
  content/src/exercises/61adeaf2-70ab-4c6c-854c-2c16f762a3c5.json
Labels: netlify-cms/pending_publish

#3479 Update exercise “640e4d9f-bb88-44af-a032-116a82f080f6”
  content/src/exercises/640e4d9f-bb88-44af-a032-116a82f080f6.json
Labels: netlify-cms/pending_publish

#3481 Update exercise “961656ea-021c-4faa-ae03-46d6ace4be4b”
  content/src/exercises/961656ea-021c-4faa-ae03-46d6ace4be4b.json
Labels: netlify-cms/pending_publish

#3482 Update exercise “961656ea-021c-4faa-ae03-46d6ace4be4b”
  content/src/exercises/961656ea-021c-4faa-ae03-46d6ace4be4b.json
Labels: netlify-cms/pending_publish

#3480 Create exercise “f4f8a536-5683-40a3-a139-5e3031687cec”
  content/src/exercises/f4f8a536-5683-40a3-a139-5e3031687cec.json
Labels: netlify-cms/pending_publish

#3483 Update collection “d9897547-18a2-4404-b12b-324458021783”
  content/src/collections/d9897547-18a2-4404-b12b-324458021783.json
Labels: netlify-cms/pending_publish

#3484 Update exercise “961656ea-021c-4faa-ae03-46d6ace4be4b”
  content/src/exercises/961656ea-021c-4faa-ae03-46d6ace4be4b.json
Labels: netlify-cms/pending_publish

#3491 Update 📱 UI “Modal.CreateSession”
  content/src/ui/Modal.CreateSession.json
Labels: netlify-cms/pending_publish

#3493 Update 📱 UI “Modal.ForgotPassword”
  content/src/ui/Modal.ForgotPassword.json
Labels: netlify-cms/pending_publish

#3494 Update 📱 UI “Modal.HostSessionByInvite”
  content/src/ui/Modal.HostSessionByInvite.json
Labels: netlify-cms/pending_publish

#3492 Update 📱 UI “Modal.Donate”
  content/src/ui/Modal.Donate.json
Labels: netlify-cms/pending_publish

#3488 Update 📱 UI “Modal.CompletedSession”
  content/src/ui/Modal.CompletedSession.json
Labels: netlify-cms/pending_publish

#3487 Update exercise “f4f8a536-5683-40a3-a139-5e3031687cec”
  content/src/exercises/f4f8a536-5683-40a3-a139-5e3031687cec.json
Labels: netlify-cms/pending_review

#3495 Update 📱 UI “Modal.HostingInviteFail”
  content/src/ui/Modal.HostingInviteFail.json
Labels: netlify-cms/pending_publish

#3498 Update 📱 UI “Modal.ProfileSettings”
  content/src/ui/Modal.ProfileSettings.json
Labels: netlify-cms/pending_publish

#3503 Update exercise “f4f8a536-5683-40a3-a139-5e3031687cec”
  content/src/exercises/f4f8a536-5683-40a3-a139-5e3031687cec.json
Labels: netlify-cms/pending_publish

#3537 Update 📱 UI “Component.CrashErrorMessage”
  content/src/ui/Component.CrashErrorMessage.json
Labels: netlify-cms/draft

#3508 Update ⚙️ Settings “exercise-defaults”
  cms/src/defaults/exercise.json
  shared/src/types/JSON.ts
Labels: netlify-cms/pending_publish

#3473 🚢 Release 2.33.0
  client/android/app/build.gradle
  client/ios/Supporting/Info.plist
  client/ios/twentyninek.xcodeproj/project.pbxproj
Labels: native release

#3539 Create exercise “2d096e25-3f0b-48da-8557-3db607b98ef8”
  content/src/exercises/2d096e25-3f0b-48da-8557-3db607b98ef8.json
Labels: netlify-cms/pending_publish

#3544 Update exercise “2d096e25-3f0b-48da-8557-3db607b98ef8”
  content/src/exercises/2d096e25-3f0b-48da-8557-3db607b98ef8.json
Labels: netlify-cms/pending_publish

#3543 Update exercise “f4f8a536-5683-40a3-a139-5e3031687cec”
  content/src/exercises/f4f8a536-5683-40a3-a139-5e3031687cec.json
Labels: netlify-cms/pending_publish

#3546 Update exercise “0bcb6eb0-fdfe-466d-8603-ae6de15fcbc5”
  content/src/exercises/0bcb6eb0-fdfe-466d-8603-ae6de15fcbc5.json
Labels: netlify-cms/pending_publish

#3547 Update exercise “3188a5ed-a1d6-451c-ae2a-f44f4df37495”
  content/src/exercises/3188a5ed-a1d6-451c-ae2a-f44f4df37495.json
Labels: netlify-cms/pending_publish

#3548 Update exercise “b18c1cff-bb43-44b1-81a1-2877cc018ab4”
  content/src/exercises/b18c1cff-bb43-44b1-81a1-2877cc018ab4.json
Labels: netlify-cms/pending_publish

#3549 Update exercise “2d096e25-3f0b-48da-8557-3db607b98ef8”
  content/src/exercises/2d096e25-3f0b-48da-8557-3db607b98ef8.json
Labels: netlify-cms/pending_publish

#3551 Update 📱 UI “Screen.Explore”
  content/src/ui/Screen.Explore.json
Labels: netlify-cms/pending_publish

#3554 Update exercise “1a53e633-6916-4fea-a072-977c4b215288”
  content/src/exercises/1a53e633-6916-4fea-a072-977c4b215288.json
Labels: netlify-cms/pending_publish

#3555 Update collection “8cb72f0d-3aad-4fe6-bf08-560b108bb439”
  content/src/collections/8cb72f0d-3aad-4fe6-bf08-560b108bb439.json
Labels: netlify-cms/pending_publish

#3556 Update exercise “2d096e25-3f0b-48da-8557-3db607b98ef8”
  content/src/exercises/2d096e25-3f0b-48da-8557-3db607b98ef8.json
Labels: netlify-cms/pending_publish

#3557 Update exercise “961656ea-021c-4faa-ae03-46d6ace4be4b”
  content/src/exercises/961656ea-021c-4faa-ae03-46d6ace4be4b.json
Labels: netlify-cms/pending_publish

#3558 Update exercise “f4f8a536-5683-40a3-a139-5e3031687cec”
  content/src/exercises/f4f8a536-5683-40a3-a139-5e3031687cec.json
Labels: netlify-cms/pending_publish

#3560 Update exercise “0bcb6eb0-fdfe-466d-8603-ae6de15fcbc5”
  content/src/exercises/0bcb6eb0-fdfe-466d-8603-ae6de15fcbc5.json
Labels: netlify-cms/pending_publish

#3561 Update exercise “b18c1cff-bb43-44b1-81a1-2877cc018ab4”
  content/src/exercises/b18c1cff-bb43-44b1-81a1-2877cc018ab4.json
Labels: netlify-cms/pending_publish

#3562 Update exercise “f4f8a536-5683-40a3-a139-5e3031687cec”
  content/src/exercises/f4f8a536-5683-40a3-a139-5e3031687cec.json
Labels: netlify-cms/pending_publish

#3567 Update exercise “961656ea-021c-4faa-ae03-46d6ace4be4b”
  content/src/exercises/961656ea-021c-4faa-ae03-46d6ace4be4b.json
Labels: netlify-cms/pending_publish

#3563 Update exercise “1a53e633-6916-4fea-a072-977c4b215288”
  content/src/exercises/1a53e633-6916-4fea-a072-977c4b215288.json
Labels: netlify-cms/pending_publish

#3565 Update exercise “0bcb6eb0-fdfe-466d-8603-ae6de15fcbc5”
  content/src/exercises/0bcb6eb0-fdfe-466d-8603-ae6de15fcbc5.json
Labels: netlify-cms/pending_publish

#3564 Update exercise “3188a5ed-a1d6-451c-ae2a-f44f4df37495”
  content/src/exercises/3188a5ed-a1d6-451c-ae2a-f44f4df37495.json
Labels: netlify-cms/pending_publish

#3566 Update exercise “b18c1cff-bb43-44b1-81a1-2877cc018ab4”
  content/src/exercises/b18c1cff-bb43-44b1-81a1-2877cc018ab4.json
Labels: netlify-cms/pending_publish

#3568 Update exercise “2d096e25-3f0b-48da-8557-3db607b98ef8”
  content/src/exercises/2d096e25-3f0b-48da-8557-3db607b98ef8.json
Labels: netlify-cms/pending_publish

#3569 Update exercise “961656ea-021c-4faa-ae03-46d6ace4be4b”
  content/src/exercises/961656ea-021c-4faa-ae03-46d6ace4be4b.json
Labels: netlify-cms/pending_publish

#3570 Update exercise “f4f8a536-5683-40a3-a139-5e3031687cec”
  content/src/exercises/f4f8a536-5683-40a3-a139-5e3031687cec.json
Labels: netlify-cms/pending_publish

#3571 Update collection “8cb72f0d-3aad-4fe6-bf08-560b108bb439”
  content/src/collections/8cb72f0d-3aad-4fe6-bf08-560b108bb439.json
Labels: netlify-cms/pending_publish

#3573 Update 📱 UI “Screen.Portal”
  content/src/ui/Screen.Portal.json
Labels: netlify-cms/pending_publish

#3572 Update 📱 UI “Screen.Journey”
  content/src/ui/Screen.Journey.json
Labels: netlify-cms/pending_publish

#3574 Update exercise “961656ea-021c-4faa-ae03-46d6ace4be4b”
  content/src/exercises/961656ea-021c-4faa-ae03-46d6ace4be4b.json
Labels: netlify-cms/pending_publish

#3575 Update exercise “2d096e25-3f0b-48da-8557-3db607b98ef8”
  content/src/exercises/2d096e25-3f0b-48da-8557-3db607b98ef8.json
Labels: netlify-cms/pending_publish

#3576 Update 📱 UI “Overlay.Session”
  content/src/ui/Overlay.Session.json
Labels: netlify-cms/pending_publish
