Repository 29ki/29k, pull requests merged in 2023-04, with the labels that each got.

#2208 🚢 Release 2.17.0
  client/android/app/build.gradle
  client/android/app/src/main/assets/modules.json
  client/android/app/src/main/java/org/twentyninek/app/cupcake/MainApplication.java
  client/android/app/src/main/java/org/twentyninek/app/cupcake/newarchitecture/videoLooper/AspectRatioFrameLayout.java
  client/android/app/src/main/java/org/twentyninek/app/cupcake/newarchitecture/videoLooper/MediaItemConfig.java
  client/android/app/src/main/java/org/twentyninek/app/cupcake/newarchitecture/videoLooper/ReactEvents.java
  client/android/app/src/main/java/org/twentyninek/app/cupcake/newarchitecture/videoLooper/ReactVideoLooperManager.java
  client/android/app/src/main/java/org/twentyninek/app/cupcake/newarchitecture/videoLooper/ReactVideoLooperPackage.java
  client/android/app/src/main/java/org/twentyninek/app/cupcake/newarchitecture/videoLooper/ReactVideoLooperView.java
  client/android/app/src/main/java/org/twentyninek/app/cupcake/newarchitecture/videoLooper/ResizeMode.java
  client/android/app/src/main/java/org/twentyninek/app/cupcake/newarchitecture/videoLooper/VideoCacheManager.java
  client/ios/Podfile
  client/ios/Podfile.lock
  client/ios/Supporting/Info.plist
  client/ios/VideoLooper-Bridging-Header.h
  client/ios/VideoLooperManager.m
  client/ios/VideoLooperManager.swift
  client/ios/VideoLooperView.swift
  client/ios/twentyninek.xcodeproj/project.pbxproj
  client/package.json
  client/src/lib/components/Sound/Sound.ts
  client/src/lib/components/VideoLooper/VideoLooper.js
  client/src/lib/daily/DailyProvider.tsx
  client/src/lib/session/components/AudioFader/AudioFader.tsx
  client/src/lib/session/components/IntroPortal/IntroPortal.tsx
  client/src/lib/session/components/OutroPortal/OutroPortal.tsx
  client/src/lib/session/components/Slides/Slides/Blocks/Video.tsx
  client/src/lib/session/components/Slides/Slides/Content.tsx
  client/src/lib/session/components/Slides/Slides/HostVideo.tsx
  client/src/lib/session/components/VideoTransition/VideoTransition.tsx
  client/src/routes/screens/LiveSession/IntroPortal.tsx
  client/types/VideoLooper.d.ts
  client/yarn.lock
Labels: native release

#2250 Create exercise “640e4d9f-bb88-44af-a032-116a82f080f6”
  content/src/exercises/640e4d9f-bb88-44af-a032-116a82f080f6.json
Labels: netlify-cms/pending_publish

#2254 Update exercise “640e4d9f-bb88-44af-a032-116a82f080f6”
  content/src/exercises/640e4d9f-bb88-44af-a032-116a82f080f6.json
Labels: netlify-cms/pending_publish

#2294 Update exercise “c5b1197a-4eec-4699-9dad-0e3d6323967b”
  content/src/exercises/c5b1197a-4eec-4699-9dad-0e3d6323967b.json
Labels: netlify-cms/pending_publish

#2293 🚢 Release 2.19.0
  client/android/app/build.gradle
  client/android/app/src/main/assets/modules.json
  client/android/app/src/main/res/drawable/thumbs_up.png
  client/android/app/src/main/res/drawable/thumbs_up_silouette.png
  client/android/link-assets-manifest.json
  client/ios/Podfile.lock
  client/ios/Supporting/Info.plist
  client/ios/link-assets-manifest.json
  client/ios/twentyninek.xcodeproj/project.pbxproj
  client/package.json
  client/react-native.config.js
  client/src/assets/images/thumbs_up.png
  client/src/assets/images/thumbs_up_silouette.png
  client/src/lib/components/Badge/Badge.tsx
  client/src/lib/components/Thumbs/Thumbs.tsx
  client/src/lib/navigation/ModalStack.tsx
  client/src/lib/navigation/constants/routes.ts
  client/src/lib/sessions/hooks/useCompletedSessions.ts
  client/src/routes/modals/CompletedSessionsModal/CompletedSessionsModal.tsx
  client/src/routes/modals/CompletedSessionsModal/components/FeedbackFilters.tsx
  client/src/routes/modals/CompletedSessionsModal/components/ModeFilters.tsx
  client/src/routes/modals/CompletedSessionsModal/hooks/useGetSessionsByFeedback.spec.ts
  client/src/routes/modals/CompletedSessionsModal/hooks/useGetSessionsByFeedback.ts
  client/src/routes/modals/SessionFeedbackModal/SessionFeedbackModal.tsx
  client/src/routes/screens/Journey/Journey.tsx
  client/src/routes/screens/Journey/components/FilterStatus.tsx
  client/src/routes/screens/Journey/components/JourneyNode.tsx
  client/src/routes/screens/Journey/types/JourneyItem.ts
  client/yarn.lock
  content/src/ui/Modal.CompletedSessions.json
  content/src/ui/Screen.Journey.json
  shared/src/constants/colors.ts
Labels: native release

#2318 Handle call interruptions
  client/ios/VideoLooperView.swift
Labels: bug, native release

#2342 Update 📱 UI “Screen.Onboarding”
  content/src/ui/Screen.Onboarding.json
Labels: netlify-cms/pending_publish

#2357 Update 📱 UI “Alert.ChangeProfilePicture”
  content/src/ui/Alert.ChangeProfilePicture.json
Labels: netlify-cms/pending_publish

#2358 Update 📱 UI “Component.AddToCalendar”
  content/src/ui/Component.AddToCalendar.json
Labels: netlify-cms/pending_publish

#2361 Update 📱 UI “Overlay.About”
  content/src/ui/Overlay.About.json
Labels: netlify-cms/pending_publish

#2360 Update 📱 UI “DeepLink.JoinSessionInvite”
  content/src/ui/DeepLink.JoinSessionInvite.json
Labels: netlify-cms/pending_publish

#2359 Update 📱 UI “Component.RequestNotificationPermission”
  content/src/ui/Component.RequestNotificationPermission.json
Labels: netlify-cms/pending_publish

#2362 Update 📱 UI “Overlay.AboutEditorial”
  content/src/ui/Overlay.AboutEditorial.json
Labels: netlify-cms/pending_publish

#2363 Update 📱 UI “Modal.CompletedSessions”
  content/src/ui/Modal.CompletedSessions.json
Labels: netlify-cms/pending_publish

#2381 Create exercise “9ac0c561-ff26-45fc-b6d5-0a983432394e-1”
  content/src/exercises/9ac0c561-ff26-45fc-b6d5-0a983432394e-1.json
Labels: netlify-cms/pending_publish

#2389 Update 📱 UI “Screen.Onboarding”
  content/src/ui/Screen.Onboarding.json
Labels: netlify-cms/pending_publish

#2390 Update exercise “b7f8731c-64d7-4c0f-9bc8-a3e50ec2eaf7”
  content/src/exercises/b7f8731c-64d7-4c0f-9bc8-a3e50ec2eaf7.json
Labels: netlify-cms/pending_publish

#2392 Update 📱 UI “Component.Tabs”
  content/src/ui/Component.Tabs.json
Labels: netlify-cms/pending_publish

#2393 Update exercise “b7f8731c-64d7-4c0f-9bc8-a3e50ec2eaf7”
  content/src/exercises/b7f8731c-64d7-4c0f-9bc8-a3e50ec2eaf7.json
Labels: netlify-cms/pending_publish

#2398 Update exercise “b18c1cff-bb43-44b1-81a1-2877cc018ab4”
  content/src/exercises/b18c1cff-bb43-44b1-81a1-2877cc018ab4.json
Labels: netlify-cms/pending_publish

#2400 Update exercise “b18c1cff-bb43-44b1-81a1-2877cc018ab4”
  content/src/exercises/b18c1cff-bb43-44b1-81a1-2877cc018ab4.json
Labels: netlify-cms/pending_publish

#2404 Create Tag “da15b7ab-dd95-4fc7-b085-2f022ab7282f”
  content/src/tags/da15b7ab-dd95-4fc7-b085-2f022ab7282f.json
Labels: netlify-cms/pending_publish

#2405 Create Tag “8558ac04-771c-4f9e-9e44-e67fc04f1c7f”
  content/src/tags/8558ac04-771c-4f9e-9e44-e67fc04f1c7f.json
Labels: netlify-cms/pending_publish

#2401 Create Tag “34100e43-2eb8-4d35-8eb0-9fa9f78e4935”
  content/src/tags/34100e43-2eb8-4d35-8eb0-9fa9f78e4935.json
Labels: netlify-cms/pending_publish

#2403 Create Tag “aef38753-75d6-4fe4-9410-4a77ca02b05f”
  content/src/tags/aef38753-75d6-4fe4-9410-4a77ca02b05f.json
Labels: netlify-cms/pending_publish

#2351 🚢 Release 2.22.0
  client/android/app/build.gradle
  client/android/app/src/main/AndroidManifest.xml
  client/android/app/src/main/assets/modules.json
  client/android/app/src/main/res/drawable/community.jpg
  client/android/link-assets-manifest.json
  client/ios/Podfile.lock
  client/ios/Supporting/Info.plist
  client/ios/VideoLooperManager.m
  client/ios/VideoLooperView.swift
  client/ios/dev.entitlements
  client/ios/link-assets-manifest.json
  client/ios/production.entitlements
  client/ios/staging.entitlements
  client/ios/twentyninek.xcodeproj/project.pbxproj
  client/package.json
  client/src/assets/images/community.jpg
  client/src/lib/components/VideoLooper/VideoLooper.js
  client/src/lib/navigation/OverlayStack.tsx
  client/src/lib/navigation/linking.ts
  client/src/routes/modals/CompletedSessionsModal/CompletedSessionsModal.tsx
  client/src/routes/screens/Journey/Journey.tsx
  client/src/routes/screens/Journey/components/JourneyNode.tsx
  client/types/VideoLooper.d.ts
  client/yarn.lock
  docs/INSTALLATION.md
Labels: native release

#2395 Create collection “68172f5c-955a-43e0-9cef-ae3bc77c9593”
  content/src/collections/68172f5c-955a-43e0-9cef-ae3bc77c9593.json
Labels: netlify-cms/pending_publish

#2396 Create collection “af1c4ac9-1bae-4cb1-8c98-e1f98a8aea66”
  content/src/collections/af1c4ac9-1bae-4cb1-8c98-e1f98a8aea66.json
Labels: netlify-cms/pending_publish

#2397 Create collection “716c2b31-612c-40c4-8e85-90f0a2af380e”
  content/src/collections/716c2b31-612c-40c4-8e85-90f0a2af380e.json
Labels: netlify-cms/pending_publish

#2451 Create Tag “9c2c08a9-7dc6-4058-bc78-016d0eb00614”
  content/src/tags/9c2c08a9-7dc6-4058-bc78-016d0eb00614.json
Labels: netlify-cms/pending_publish

#2449 Update Tag “aef38753-75d6-4fe4-9410-4a77ca02b05f”
  content/src/tags/aef38753-75d6-4fe4-9410-4a77ca02b05f.json
Labels: netlify-cms/pending_publish

#2450 Create Tag “db34d82a-4c48-4ddd-9de5-f562d8aa1bc9”
  content/src/tags/db34d82a-4c48-4ddd-9de5-f562d8aa1bc9.json
Labels: netlify-cms/pending_publish

#2453 Update 📱 UI “Component.Tabs”
  content/src/ui/Component.Tabs.json
Labels: netlify-cms/pending_publish

#2463 Update exercise “5b0dea9f-c665-41ce-a779-601d0cfa433d”
  content/src/exercises/5b0dea9f-c665-41ce-a779-601d0cfa433d.json
Labels: netlify-cms/pending_publish

#2461 Update exercise “3188a5ed-a1d6-451c-ae2a-f44f4df37495”
  content/src/exercises/3188a5ed-a1d6-451c-ae2a-f44f4df37495.json
Labels: netlify-cms/pending_publish

#2467 Update exercise “c5b1197a-4eec-4699-9dad-0e3d6323967b”
  content/src/exercises/c5b1197a-4eec-4699-9dad-0e3d6323967b.json
Labels: netlify-cms/pending_publish

#2470 Update exercise “0bcb6eb0-fdfe-466d-8603-ae6de15fcbc5”
  content/src/exercises/0bcb6eb0-fdfe-466d-8603-ae6de15fcbc5.json
Labels: netlify-cms/pending_publish

#2464 Update exercise “b7f8731c-64d7-4c0f-9bc8-a3e50ec2eaf7”
  content/src/exercises/b7f8731c-64d7-4c0f-9bc8-a3e50ec2eaf7.json
Labels: netlify-cms/pending_publish

#2462 Update exercise “640e4d9f-bb88-44af-a032-116a82f080f6”
  content/src/exercises/640e4d9f-bb88-44af-a032-116a82f080f6.json
Labels: netlify-cms/pending_publish

#2469 Update exercise “9ac0c561-ff26-45fc-b6d5-0a983432394e”
  content/src/exercises/9ac0c561-ff26-45fc-b6d5-0a983432394e.json
Labels: netlify-cms/pending_publish

#2465 Update exercise “095f9642-73b6-4c9a-ae9a-ea7dea7363f5”
  content/src/exercises/095f9642-73b6-4c9a-ae9a-ea7dea7363f5.json
Labels: netlify-cms/pending_publish

#2466 Update exercise “41ba136c-4950-42fc-bd6b-761b829ee371”
  content/src/exercises/41ba136c-4950-42fc-bd6b-761b829ee371.json
Labels: netlify-cms/pending_publish

#2458 Update exercise “b18c1cff-bb43-44b1-81a1-2877cc018ab4”
  content/src/exercises/b18c1cff-bb43-44b1-81a1-2877cc018ab4.json
Labels: netlify-cms/pending_publish

#2459 Update exercise “ea0b48c1-745e-418d-93e7-2d8a6cd72898”
  content/src/exercises/ea0b48c1-745e-418d-93e7-2d8a6cd72898.json
Labels: netlify-cms/pending_publish

#2457 Update exercise “185889ec-753b-4e2c-8322-3004013e8a6e”
  content/src/exercises/185889ec-753b-4e2c-8322-3004013e8a6e.json
Labels: netlify-cms/pending_publish

#2456 Update exercise “94575e97-fe03-4bfd-94a6-50aaf721d47e”
  content/src/exercises/94575e97-fe03-4bfd-94a6-50aaf721d47e.json
Labels: netlify-cms/pending_publish

#2468 Update exercise “1e96f73b-8193-4aa6-a52c-31355eac3c08”
  content/src/exercises/1e96f73b-8193-4aa6-a52c-31355eac3c08.json
Labels: netlify-cms/pending_publish

#2476 Update collection “68172f5c-955a-43e0-9cef-ae3bc77c9593”
  content/src/collections/68172f5c-955a-43e0-9cef-ae3bc77c9593.json
Labels: netlify-cms/pending_publish

#2479 Update 📱 UI “Component.BylineUser”
  content/src/ui/Component.BylineUser.json
Labels: netlify-cms/pending_publish

#2481 Update 📱 UI “Screen.Explore”
  content/src/ui/Screen.Explore.json
Labels: netlify-cms/pending_publish

#2482 Update 📱 UI “Screen.Journey”
  content/src/ui/Screen.Journey.json
Labels: netlify-cms/pending_publish

#2441 🚢 Release 2.23.0
  client/android/app/build.gradle
  client/android/app/src/main/assets/modules.json
  client/ios/Podfile.lock
  client/ios/Supporting/Info.plist
  client/ios/twentyninek.xcodeproj/project.pbxproj
  client/package.json
  client/yarn.lock
Labels: native release

#2485 Show video while navigating to session
  client/ios/VideoLooperView.swift
  client/src/lib/session/components/IntroPortal/IntroPortal.tsx
Labels: native release

#2493 Update exercise “1e96f73b-8193-4aa6-a52c-31355eac3c08”
  content/src/exercises/1e96f73b-8193-4aa6-a52c-31355eac3c08.json
Labels: netlify-cms/pending_publish

#2491 Update exercise “095f9642-73b6-4c9a-ae9a-ea7dea7363f5”
  content/src/exercises/095f9642-73b6-4c9a-ae9a-ea7dea7363f5.json
Labels: netlify-cms/pending_publish

#2489 Update exercise “5b0dea9f-c665-41ce-a779-601d0cfa433d”
  content/src/exercises/5b0dea9f-c665-41ce-a779-601d0cfa433d.json
Labels: netlify-cms/pending_publish

#2488 Update exercise “ea0b48c1-745e-418d-93e7-2d8a6cd72898”
  content/src/exercises/ea0b48c1-745e-418d-93e7-2d8a6cd72898.json
Labels: netlify-cms/pending_publish

#2487 Update exercise “b18c1cff-bb43-44b1-81a1-2877cc018ab4”
  content/src/exercises/b18c1cff-bb43-44b1-81a1-2877cc018ab4.json
Labels: netlify-cms/pending_publish

#2490 Update exercise “b7f8731c-64d7-4c0f-9bc8-a3e50ec2eaf7”
  content/src/exercises/b7f8731c-64d7-4c0f-9bc8-a3e50ec2eaf7.json
Labels: netlify-cms/pending_publish

#2498 Update collection “716c2b31-612c-40c4-8e85-90f0a2af380e”
  content/src/collections/716c2b31-612c-40c4-8e85-90f0a2af380e.json
Labels: netlify-cms/pending_publish

#2501 Create exercise “1a53e633-6916-4fea-a072-977c4b215288”
  content/src/exercises/1a53e633-6916-4fea-a072-977c4b215288.json
Labels: netlify-cms/pending_publish

#2503 Update exercise “640e4d9f-bb88-44af-a032-116a82f080f6”
  content/src/exercises/640e4d9f-bb88-44af-a032-116a82f080f6.json
Labels: netlify-cms/pending_publish

#2504 Update 📱 UI “Screen.Journey”
  content/src/ui/Screen.Journey.json
Labels: netlify-cms/pending_publish

#2505 Update 📱 UI “Screen.Onboarding”
  content/src/ui/Screen.Onboarding.json
Labels: netlify-cms/pending_publish

#2507 Update Tag “34100e43-2eb8-4d35-8eb0-9fa9f78e4935”
  content/src/tags/34100e43-2eb8-4d35-8eb0-9fa9f78e4935.json
Labels: netlify-cms/pending_publish

#2508 Update Tag “8558ac04-771c-4f9e-9e44-e67fc04f1c7f”
  content/src/tags/8558ac04-771c-4f9e-9e44-e67fc04f1c7f.json
Labels: netlify-cms/pending_publish

#2509 Update Tag “9c2c08a9-7dc6-4058-bc78-016d0eb00614”
  content/src/tags/9c2c08a9-7dc6-4058-bc78-016d0eb00614.json
Labels: netlify-cms/pending_publish

#2511 Update Tag “cfc00217-f65b-4a4d-8b82-8ccc8f852dd6”
  content/src/tags/cfc00217-f65b-4a4d-8b82-8ccc8f852dd6.json
Labels: netlify-cms/pending_publish

#2510 Update Tag “aef38753-75d6-4fe4-9410-4a77ca02b05f”
  content/src/tags/aef38753-75d6-4fe4-9410-4a77ca02b05f.json
Labels: netlify-cms/pending_publish

#2512 Update Tag “da15b7ab-dd95-4fc7-b085-2f022ab7282f”
  content/src/tags/da15b7ab-dd95-4fc7-b085-2f022ab7282f.json
Labels: netlify-cms/pending_publish

#2513 Update Tag “db34d82a-4c48-4ddd-9de5-f562d8aa1bc9”
  content/src/tags/db34d82a-4c48-4ddd-9de5-f562d8aa1bc9.json
Labels: netlify-cms/pending_publish

#2516 Update 📱 UI “Modal.CompletedSessions”
  content/src/ui/Modal.CompletedSessions.json
Labels: netlify-cms/pending_publish

#2517 Update 📱 UI “Modal.CreateSession”
  content/src/ui/Modal.CreateSession.json
Labels: netlify-cms/pending_publish
