Repository 29ki/29k, pull requests merged in 2023-09, with the labels that each got.

#3577 Update exercise “2d096e25-3f0b-48da-8557-3db607b98ef8”
  content/src/exercises/2d096e25-3f0b-48da-8557-3db607b98ef8.json
Labels: netlify-cms/pending_publish

#3580 Update exercise “f4f8a536-5683-40a3-a139-5e3031687cec”
  content/src/exercises/f4f8a536-5683-40a3-a139-5e3031687cec.json
Labels: netlify-cms/pending_publish

#3582 Update collection “8cb72f0d-3aad-4fe6-bf08-560b108bb439”
  content/src/collections/8cb72f0d-3aad-4fe6-bf08-560b108bb439.json
Labels: netlify-cms/pending_publish

#3581 Update exercise “2d096e25-3f0b-48da-8557-3db607b98ef8”
  content/src/exercises/2d096e25-3f0b-48da-8557-3db607b98ef8.json
Labels: netlify-cms/pending_publish

#3584 Update 📱 UI “Modal.RequestPublicHost”
  content/src/ui/Modal.RequestPublicHost.json
Labels: netlify-cms/pending_publish

#3585 Update 📱 UI “Modal.SessionError”
  content/src/ui/Modal.SessionError.json
Labels: netlify-cms/pending_publish

#3586 Update 📱 UI “Modal.SignIn”
  content/src/ui/Modal.SignIn.json
Labels: netlify-cms/pending_publish

#3587 Update 📱 UI “Modal.UpgradeAccount”
  content/src/ui/Modal.UpgradeAccount.json
Labels: netlify-cms/pending_publish

#3589 Update exercise “f4f8a536-5683-40a3-a139-5e3031687cec”
  content/src/exercises/f4f8a536-5683-40a3-a139-5e3031687cec.json
Labels: netlify-cms/pending_publish

#3590 Update 📱 UI “Overlay.CommunityEditorial”
  content/src/ui/Overlay.CommunityEditorial.json
Labels: netlify-cms/pending_publish

#3588 Update 📱 UI “Overlay.AboutEditorial”
  content/src/ui/Overlay.AboutEditorial.json
Labels: netlify-cms/pending_publish

#3583 Update 📱 UI “Component.Counter”
  content/src/ui/Component.Counter.json
Labels: netlify-cms/pending_publish

#3595 Update 📱 UI “Screen.KillSwitch”
  content/src/ui/Screen.KillSwitch.json
Labels: netlify-cms/pending_publish

#3592 Update 📱 UI “Screen.ChangingRoom”
  content/src/ui/Screen.ChangingRoom.json
Labels: netlify-cms/pending_publish

#3594 Update 📱 UI “Screen.Home”
  content/src/ui/Screen.Home.json
Labels: netlify-cms/pending_publish

#3591 Update 📱 UI “Overlay.Session”
  content/src/ui/Overlay.Session.json
Labels: netlify-cms/pending_publish

#3593 Update 📱 UI “Screen.Collection”
  content/src/ui/Screen.Collection.json
Labels: netlify-cms/pending_publish

#3596 Update collection “8cb72f0d-3aad-4fe6-bf08-560b108bb439”
  content/src/collections/8cb72f0d-3aad-4fe6-bf08-560b108bb439.json
Labels: netlify-cms/pending_publish

#3598 Update 📱 UI “Screen.Session”
  content/src/ui/Screen.Session.json
Labels: netlify-cms/pending_publish

#3599 Update 📱 UI “Overlay.CommunityEditorial”
  content/src/ui/Overlay.CommunityEditorial.json
Labels: netlify-cms/pending_publish

#3601 Update exercise “0bcb6eb0-fdfe-466d-8603-ae6de15fcbc5”
  content/src/exercises/0bcb6eb0-fdfe-466d-8603-ae6de15fcbc5.json
Labels: netlify-cms/draft

#3602 Update exercise “961656ea-021c-4faa-ae03-46d6ace4be4b”
  content/src/exercises/961656ea-021c-4faa-ae03-46d6ace4be4b.json
Labels: netlify-cms/pending_publish

#3606 Update exercise “f4f8a536-5683-40a3-a139-5e3031687cec”
  content/src/exercises/f4f8a536-5683-40a3-a139-5e3031687cec.json
Labels: netlify-cms/pending_publish

#3607 Update collection “8cb72f0d-3aad-4fe6-bf08-560b108bb439”
  content/src/collections/8cb72f0d-3aad-4fe6-bf08-560b108bb439.json
Labels: netlify-cms/draft

#3608 Update collection “d9897547-18a2-4404-b12b-324458021783”
  content/src/collections/d9897547-18a2-4404-b12b-324458021783.json
Labels: netlify-cms/pending_publish

#3610 Update 📱 UI “Screen.Explore”
  content/src/ui/Screen.Explore.json
Labels: netlify-cms/pending_publish

#3579 🚢 Release 2.34.0
  client/android/app/build.gradle
  client/ios/Podfile.lock
  client/ios/Supporting/Info.plist
  client/ios/twentyninek.xcodeproj/project.pbxproj
  client/package.json
  client/yarn.lock
Labels: native release

#3639 Update 🪴 Other “all-contributorsrc”
  .all-contributorsrc
  README.md
Labels: netlify-cms/draft

#3640 Update exercise “9ac0c561-ff26-45fc-b6d5-0a983432394e”
  content/src/exercises/9ac0c561-ff26-45fc-b6d5-0a983432394e.json
Labels: netlify-cms/pending_publish

#3646 Live session onboarding
  client/src/lib/components/Icons/FilmCameraCheck/FilmCameraCheck.tsx
  client/src/lib/components/Icons/Logo/Logo.tsx
  client/src/lib/components/Icons/index.ts
  client/src/lib/daily/DailyProvider.tsx
  client/src/lib/metrics/types/Events.ts
  client/src/lib/session/components/Participants/AudioDeniedIndicator.tsx
  client/src/lib/session/components/Participants/AudioToggler.tsx
  client/src/lib/session/components/Participants/Participant.tsx
  client/src/lib/session/components/Participants/VideoDeniedIndicator.tsx
  client/src/lib/session/hooks/useCheckPermissions.spec.ts
  client/src/lib/session/hooks/useCheckPermissions.ts
  client/src/lib/session/hooks/useLiveSessionMetricEvents.ts
  client/src/routes/screens/LiveSession/ChangingRoom.tsx
  client/src/routes/screens/LiveSession/ChangingRoom/components/HairCheck.tsx
  client/src/routes/screens/LiveSession/ChangingRoom/components/Loading.tsx
  client/src/routes/screens/LiveSession/ChangingRoom/components/SessionOnboarding.tsx
  client/src/routes/screens/LiveSession/ChangingRoom/index.tsx
  client/src/routes/screens/LiveSession/Session.tsx
  content/src/ui/Screen.ChangingRoom.json
Labels: native release

#3637 🚢 Release 2.35.0
  client/__mocks__/react-native-permissions.js
  client/android/app/build.gradle
  client/ios/Podfile
  client/ios/Podfile.lock
  client/ios/Supporting/Info.plist
  client/ios/twentyninek.xcodeproj/project.pbxproj
  client/package.json
  client/src/lib/components/Icons/FilmCameraCheck/FilmCameraCheck.tsx
  client/src/lib/components/Icons/Logo/Logo.tsx
  client/src/lib/components/Icons/index.ts
  client/src/lib/daily/DailyProvider.tsx
  client/src/lib/metrics/types/Events.ts
  client/src/lib/session/components/Participants/AudioDeniedIndicator.tsx
  client/src/lib/session/components/Participants/AudioToggler.tsx
  client/src/lib/session/components/Participants/Participant.tsx
  client/src/lib/session/components/Participants/VideoDeniedIndicator.tsx
  client/src/lib/session/hooks/useCheckPermissions.spec.ts
  client/src/lib/session/hooks/useCheckPermissions.ts
  client/src/lib/session/hooks/useLiveSessionMetricEvents.ts
  client/src/routes/screens/LiveSession/ChangingRoom.tsx
  client/src/routes/screens/LiveSession/ChangingRoom/components/HairCheck.tsx
  client/src/routes/screens/LiveSession/ChangingRoom/components/Loading.tsx
  client/src/routes/screens/LiveSession/ChangingRoom/components/SessionOnboarding.tsx
  client/src/routes/screens/LiveSession/ChangingRoom/index.tsx
  client/src/routes/screens/LiveSession/Session.tsx
  client/yarn.lock
  content/src/ui/Screen.ChangingRoom.json
  functions/yarn.lock
Labels: native release

#3652 Update 📱 UI “Modal.SessionFeedback”
  content/src/ui/Modal.SessionFeedback.json
Labels: netlify-cms/pending_publish

#3683 Update collection “d9897547-18a2-4404-b12b-324458021783”
  content/src/collections/d9897547-18a2-4404-b12b-324458021783.json
Labels: netlify-cms/pending_publish

#3684 Create collection “0eda04e3-4b45-44d6-b779-7b40f43f966c”
  content/src/collections/0eda04e3-4b45-44d6-b779-7b40f43f966c.json
Labels: netlify-cms/pending_publish

#3685 Create exercise “12f448d2-39bc-4232-b8cf-b6cb570c7e00”
  content/src/exercises/12f448d2-39bc-4232-b8cf-b6cb570c7e00.json
Labels: netlify-cms/pending_publish

#3680 Mindful minutes
  client/__mocks__/@kingstinct/react-native-healthkit.js
  client/ios/Podfile.lock
  client/ios/Supporting/Info.plist
  client/ios/dev.entitlements
  client/ios/production.entitlements
  client/ios/staging.entitlements
  client/package.json
  client/src/lib/metrics/types/Events.ts
  client/src/lib/mindfulMinutes/hooks/useConfirmLogMindfulMinutes.spec.ts
  client/src/lib/mindfulMinutes/hooks/useConfirmLogMindfulMinutes.ts
  client/src/lib/mindfulMinutes/hooks/useLogMindfulMinutes.spec.ts
  client/src/lib/mindfulMinutes/hooks/useLogMindfulMinutes.ts
  client/src/lib/mindfulMinutes/lib/logMindfulMinutes.android.spec.ts
  client/src/lib/mindfulMinutes/lib/logMindfulMinutes.android.ts
  client/src/lib/mindfulMinutes/lib/logMindfulMinutes.ios.spec.ts
  client/src/lib/mindfulMinutes/lib/logMindfulMinutes.ios.ts
  client/src/lib/session/hooks/useStartAsyncSession.ts
  client/src/lib/user/state/state.ts
  client/src/routes/modals/ProfileSettingsModal/ProfileSettingsModal.tsx
  client/src/routes/screens/AsyncSession/IntroPortal.tsx
  client/src/routes/screens/AsyncSession/Session.tsx
  client/src/routes/screens/LiveSession/IntroPortal.tsx
  client/src/routes/screens/LiveSession/Session.tsx
  client/tsconfig.json
  client/yarn.lock
  content/src/ui/Component.ConfirmLogMindfulMinutes.json
  content/src/ui/Modal.ProfileSettings.json
Labels: native release

#3689 Update exercise “12f448d2-39bc-4232-b8cf-b6cb570c7e00”
  content/src/exercises/12f448d2-39bc-4232-b8cf-b6cb570c7e00.json
Labels: netlify-cms/pending_publish

#3681 🚢 Release 2.36.0
  client/__mocks__/@kingstinct/react-native-healthkit.js
  client/android/app/build.gradle
  client/fastlane/Gemfile.lock
  client/ios/Podfile.lock
  client/ios/Supporting/Info.plist
  client/ios/dev.entitlements
  client/ios/production.entitlements
  client/ios/staging.entitlements
  client/ios/twentyninek.xcodeproj/project.pbxproj
  client/package.json
  client/src/lib/metrics/types/Events.ts
  client/src/lib/mindfulMinutes/hooks/useConfirmLogMindfulMinutes.spec.ts
  client/src/lib/mindfulMinutes/hooks/useConfirmLogMindfulMinutes.ts
  client/src/lib/mindfulMinutes/hooks/useLogMindfulMinutes.spec.ts
  client/src/lib/mindfulMinutes/hooks/useLogMindfulMinutes.ts
  client/src/lib/mindfulMinutes/lib/logMindfulMinutes.android.spec.ts
  client/src/lib/mindfulMinutes/lib/logMindfulMinutes.android.ts
  client/src/lib/mindfulMinutes/lib/logMindfulMinutes.ios.spec.ts
  client/src/lib/mindfulMinutes/lib/logMindfulMinutes.ios.ts
  client/src/lib/session/hooks/useStartAsyncSession.ts
  client/src/lib/user/state/state.ts
  client/src/routes/modals/ProfileSettingsModal/ProfileSettingsModal.tsx
  client/src/routes/screens/AsyncSession/IntroPortal.tsx
  client/src/routes/screens/AsyncSession/Session.tsx
  client/src/routes/screens/LiveSession/IntroPortal.tsx
  client/src/routes/screens/LiveSession/Session.tsx
  client/tsconfig.json
  client/yarn.lock
  content/src/ui/Component.ConfirmLogMindfulMinutes.json
  content/src/ui/Modal.ProfileSettings.json
Labels: native release

#3724 Create exercise “fff6f8da-f69c-458f-8905-acee04bd1a1d”
  content/src/exercises/fff6f8da-f69c-458f-8905-acee04bd1a1d.json
Labels: netlify-cms/pending_publish

#3725 Create exercise “648e1802-eb45-47b0-a42e-dd986669a4eb”
  content/src/exercises/648e1802-eb45-47b0-a42e-dd986669a4eb.json
Labels: netlify-cms/pending_publish

#3733 Create exercise “c7911238-ca9f-4499-9cae-63dfcd0c79c5”
  content/src/exercises/c7911238-ca9f-4499-9cae-63dfcd0c79c5.json
Labels: netlify-cms/pending_publish

#3727 🚢 Release 2.37.0
  client/android/app/build.gradle
  client/ios/Podfile.lock
  client/ios/Supporting/Info.plist
  client/ios/twentyninek.xcodeproj/project.pbxproj
  client/package.json
  client/yarn.lock
Labels: native release

#3767 Create exercise “5b69ff57-10c4-4288-afc7-a6f6ed212531”
  content/src/exercises/5b69ff57-10c4-4288-afc7-a6f6ed212531.json
Labels: netlify-cms/pending_publish

#3768 Update exercise “c7911238-ca9f-4499-9cae-63dfcd0c79c5”
  content/src/exercises/c7911238-ca9f-4499-9cae-63dfcd0c79c5.json
Labels: netlify-cms/pending_publish
