Repository 29ki/29k, pull requests merged in 2023-03, with the labels that each got.

#1993 Update 🪴 Other “all-contributorsrc”
  .all-contributorsrc
Labels: netlify-cms/draft

#1872 🚢 Release 2.15.3
  client/android/app/build.gradle
  client/android/app/src/main/assets/modules.json
  client/ios/Podfile.lock
  client/ios/Supporting/Info.plist
  client/ios/twentyninek.xcodeproj/project.pbxproj
  client/package.json
  client/yarn.lock
Labels: native release

#1996 Update exercise “185889ec-753b-4e2c-8322-3004013e8a6e”
  content/src/exercises/185889ec-753b-4e2c-8322-3004013e8a6e.json
Labels: netlify-cms/pending_publish

#1997 Update exercise “185889ec-753b-4e2c-8322-3004013e8a6e”
  content/src/exercises/185889ec-753b-4e2c-8322-3004013e8a6e.json
Labels: netlify-cms/pending_publish

#1998 Update exercise “5b0dea9f-c665-41ce-a779-601d0cfa433d”
  content/src/exercises/5b0dea9f-c665-41ce-a779-601d0cfa433d.json
Labels: netlify-cms/pending_publish

#1999 Update 📱 UI “Screen.Collection”
  content/src/ui/Screen.Collection.json
Labels: netlify-cms/pending_publish

#2000 Update exercise “185889ec-753b-4e2c-8322-3004013e8a6e”
  content/src/exercises/185889ec-753b-4e2c-8322-3004013e8a6e.json
Labels: netlify-cms/pending_publish

#2006 Update Tag “43a6dc0d-d866-4b79-9453-13c44e906128”
  content/src/tags/43a6dc0d-d866-4b79-9453-13c44e906128.json
Labels: netlify-cms/pending_publish

#2008 Update 🪴 Other “all-contributorsrc”
  .all-contributorsrc
Labels: netlify-cms/pending_publish

#2009 Update 🪴 Other “all-contributorsrc”
  .all-contributorsrc
Labels: netlify-cms/pending_publish

#2037 Update exercise “5b0dea9f-c665-41ce-a779-601d0cfa433d”
  content/src/exercises/5b0dea9f-c665-41ce-a779-601d0cfa433d.json
Labels: netlify-cms/pending_publish

#2041 Update exercise “9ac0c561-ff26-45fc-b6d5-0a983432394e”
  content/src/exercises/9ac0c561-ff26-45fc-b6d5-0a983432394e.json
Labels: netlify-cms/pending_publish

#2042 Update exercise “5b0dea9f-c665-41ce-a779-601d0cfa433d”
  content/src/exercises/5b0dea9f-c665-41ce-a779-601d0cfa433d.json
Labels: netlify-cms/pending_publish

#2004 🚢 Release 2.15.4
  client/android/app/build.gradle
  client/android/app/src/main/assets/modules.json
  client/ios/Podfile.lock
  client/ios/Supporting/Info.plist
  client/ios/twentyninek.xcodeproj/project.pbxproj
  client/package.json
  client/src/lib/navigation/OverlayStack.tsx
  client/src/routes/overlays/AboutEditorialOverlay/AboutEditorialOverlay.tsx
  client/src/routes/overlays/AboutOverlay/AboutOverlay.tsx
  client/src/routes/overlays/CommunityEditorialOverlay/CommunityEditorialOverlay.tsx
  client/yarn.lock
Labels: native release

#2094 Update exercise “1e96f73b-8193-4aa6-a52c-31355eac3c08”
  content/src/exercises/1e96f73b-8193-4aa6-a52c-31355eac3c08.json
Labels: netlify-cms/pending_publish

#2095 Create exercise “0bcb6eb0-fdfe-466d-8603-ae6de15fcbc5”
  content/src/exercises/0bcb6eb0-fdfe-466d-8603-ae6de15fcbc5.json
Labels: netlify-cms/pending_publish

#2098 Update exercise “b18c1cff-bb43-44b1-81a1-2877cc018ab4”
  content/src/exercises/b18c1cff-bb43-44b1-81a1-2877cc018ab4.json
Labels: netlify-cms/pending_publish

#2097 Update exercise “c5b1197a-4eec-4699-9dad-0e3d6323967b”
  content/src/exercises/c5b1197a-4eec-4699-9dad-0e3d6323967b.json
Labels: netlify-cms/pending_publish

#2101 Update exercise “ea0b48c1-745e-418d-93e7-2d8a6cd72898”
  content/src/exercises/ea0b48c1-745e-418d-93e7-2d8a6cd72898.json
Labels: netlify-cms/pending_publish

#2102 Update exercise “b18c1cff-bb43-44b1-81a1-2877cc018ab4”
  content/src/exercises/b18c1cff-bb43-44b1-81a1-2877cc018ab4.json
Labels: netlify-cms/pending_publish

#2105 Update 📱 UI “Overlay.AboutEditorial”
  content/src/ui/Overlay.AboutEditorial.json
Labels: netlify-cms/pending_publish

#2106 Update 📱 UI “Overlay.CommunityEditorial”
  content/src/ui/Overlay.CommunityEditorial.json
Labels: netlify-cms/pending_publish

#2107 Update exercise “c5b1197a-4eec-4699-9dad-0e3d6323967b”
  content/src/exercises/c5b1197a-4eec-4699-9dad-0e3d6323967b.json
Labels: netlify-cms/pending_publish

#2109 Update exercise “c5b1197a-4eec-4699-9dad-0e3d6323967b”
  content/src/exercises/c5b1197a-4eec-4699-9dad-0e3d6323967b.json
Labels: netlify-cms/pending_publish

#2110 Update 📱 UI “Overlay.CommunityEditorial”
  content/src/ui/Overlay.CommunityEditorial.json
Labels: netlify-cms/pending_publish

#2111 Update exercise “ea0b48c1-745e-418d-93e7-2d8a6cd72898”
  content/src/exercises/ea0b48c1-745e-418d-93e7-2d8a6cd72898.json
Labels: netlify-cms/pending_publish

#2147 Update 📱 UI “Overlay.CommunityEditorial”
  content/src/ui/Overlay.CommunityEditorial.json
Labels: netlify-cms/pending_publish

#2148 Update 📱 UI “Overlay.AboutEditorial”
  content/src/ui/Overlay.AboutEditorial.json
Labels: netlify-cms/pending_publish

#2150 Update exercise “095f9642-73b6-4c9a-ae9a-ea7dea7363f5”
  content/src/exercises/095f9642-73b6-4c9a-ae9a-ea7dea7363f5.json
Labels: netlify-cms/pending_publish

#2169 Update 🪴 Other “all-contributorsrc”
  .all-contributorsrc
Labels: netlify-cms/pending_publish

#2170 Update exercise “c5b1197a-4eec-4699-9dad-0e3d6323967b”
  content/src/exercises/c5b1197a-4eec-4699-9dad-0e3d6323967b.json
Labels: netlify-cms/pending_publish

#2171 Update exercise “b18c1cff-bb43-44b1-81a1-2877cc018ab4”
  content/src/exercises/b18c1cff-bb43-44b1-81a1-2877cc018ab4.json
Labels: netlify-cms/pending_publish

#2173 Update exercise “095f9642-73b6-4c9a-ae9a-ea7dea7363f5”
  content/src/exercises/095f9642-73b6-4c9a-ae9a-ea7dea7363f5.json
Labels: netlify-cms/pending_publish
