Repository 29ki/29k, pull requests merged in 2023-12, with the labels that each got.

#4279 Create Exercise “db239a42-135a-4941-bdf2-92d58107094a”
  content/src/exercises/db239a42-135a-4941-bdf2-92d58107094a.json
Labels: netlify-cms/pending_publish

#4309 Update Exercise “b18c1cff-bb43-44b1-81a1-2877cc018ab4”
  content/src/exercises/b18c1cff-bb43-44b1-81a1-2877cc018ab4.json
Labels: netlify-cms/pending_publish

#4310 Create Exercise “654551b4-1226-485e-9424-4d86d93240ff”
  content/src/exercises/654551b4-1226-485e-9424-4d86d93240ff.json
Labels: netlify-cms/pending_publish

#4311 Create Exercise “9a4834e6-8d3f-420b-88e3-dd3df9a98001”
  content/src/exercises/9a4834e6-8d3f-420b-88e3-dd3df9a98001.json
Labels: netlify-cms/pending_publish

#4312 Create Collection “be8d8f71-1b30-4f9a-80cb-616ff24e8db9”
  content/src/collections/be8d8f71-1b30-4f9a-80cb-616ff24e8db9.json
Labels: netlify-cms/pending_publish

#4313 Update Collection “be8d8f71-1b30-4f9a-80cb-616ff24e8db9”
  content/src/collections/be8d8f71-1b30-4f9a-80cb-616ff24e8db9.json
Labels: netlify-cms/pending_publish

#4318 Update Exercise “c0e6d8d2-163a-4c2d-a0af-250eef846054”
  content/src/exercises/c0e6d8d2-163a-4c2d-a0af-250eef846054.json
Labels: netlify-cms/pending_publish

#4317 Update Exercise “db239a42-135a-4941-bdf2-92d58107094a”
  content/src/exercises/db239a42-135a-4941-bdf2-92d58107094a.json
Labels: netlify-cms/pending_publish

#4315 Update Exercise “9a4834e6-8d3f-420b-88e3-dd3df9a98001”
  content/src/exercises/9a4834e6-8d3f-420b-88e3-dd3df9a98001.json
Labels: netlify-cms/pending_publish

#4314 Update Exercise “654551b4-1226-485e-9424-4d86d93240ff”
  content/src/exercises/654551b4-1226-485e-9424-4d86d93240ff.json
Labels: netlify-cms/pending_publish

#4320 Update Exercise “654551b4-1226-485e-9424-4d86d93240ff”
  content/src/exercises/654551b4-1226-485e-9424-4d86d93240ff.json
Labels: netlify-cms/pending_publish

#4321 Update Exercise “9a4834e6-8d3f-420b-88e3-dd3df9a98001”
  content/src/exercises/9a4834e6-8d3f-420b-88e3-dd3df9a98001.json
Labels: netlify-cms/pending_publish

#4322 Update Tag “8558ac04-771c-4f9e-9e44-e67fc04f1c7f”
  content/src/tags/8558ac04-771c-4f9e-9e44-e67fc04f1c7f.json
Labels: netlify-cms/pending_publish

#4323 Update Tag “da15b7ab-dd95-4fc7-b085-2f022ab7282f”
  content/src/tags/da15b7ab-dd95-4fc7-b085-2f022ab7282f.json
Labels: netlify-cms/pending_publish

#4324 Update Tag “aef38753-75d6-4fe4-9410-4a77ca02b05f”
  content/src/tags/aef38753-75d6-4fe4-9410-4a77ca02b05f.json
Labels: netlify-cms/pending_publish

#4330 Update Exercise “9a4834e6-8d3f-420b-88e3-dd3df9a98001”
  content/src/exercises/9a4834e6-8d3f-420b-88e3-dd3df9a98001.json
Labels: netlify-cms/pending_publish

#4329 Update Exercise “654551b4-1226-485e-9424-4d86d93240ff”
  content/src/exercises/654551b4-1226-485e-9424-4d86d93240ff.json
Labels: netlify-cms/pending_publish

#4325 Update Exercise “db239a42-135a-4941-bdf2-92d58107094a”
  content/src/exercises/db239a42-135a-4941-bdf2-92d58107094a.json
Labels: netlify-cms/pending_publish

#4326 Update Exercise “0d4c9833-6a11-4b1a-8d1e-4467db6f24ea”
  content/src/exercises/0d4c9833-6a11-4b1a-8d1e-4467db6f24ea.json
Labels: netlify-cms/pending_publish

#4328 Update Exercise “c0e6d8d2-163a-4c2d-a0af-250eef846054”
  content/src/exercises/c0e6d8d2-163a-4c2d-a0af-250eef846054.json
Labels: netlify-cms/pending_publish

#4333 Update Collection “be8d8f71-1b30-4f9a-80cb-616ff24e8db9”
  content/src/collections/be8d8f71-1b30-4f9a-80cb-616ff24e8db9.json
Labels: netlify-cms/pending_publish

#4339 Update Exercise “db239a42-135a-4941-bdf2-92d58107094a”
  content/src/exercises/db239a42-135a-4941-bdf2-92d58107094a.json
Labels: netlify-cms/pending_publish

#4338 Update Exercise “c0e6d8d2-163a-4c2d-a0af-250eef846054”
  content/src/exercises/c0e6d8d2-163a-4c2d-a0af-250eef846054.json
Labels: netlify-cms/pending_publish

#4336 Update Exercise “9a4834e6-8d3f-420b-88e3-dd3df9a98001”
  content/src/exercises/9a4834e6-8d3f-420b-88e3-dd3df9a98001.json
Labels: netlify-cms/pending_publish

#4337 Update Exercise “0d4c9833-6a11-4b1a-8d1e-4467db6f24ea”
  content/src/exercises/0d4c9833-6a11-4b1a-8d1e-4467db6f24ea.json
Labels: netlify-cms/pending_publish

#4335 Update Exercise “654551b4-1226-485e-9424-4d86d93240ff”
  content/src/exercises/654551b4-1226-485e-9424-4d86d93240ff.json
Labels: netlify-cms/pending_publish

#4350 Update Exercise “db239a42-135a-4941-bdf2-92d58107094a”
  content/src/exercises/db239a42-135a-4941-bdf2-92d58107094a.json
Labels: netlify-cms/pending_publish

#4351 Update Exercise “0d4c9833-6a11-4b1a-8d1e-4467db6f24ea”
  content/src/exercises/0d4c9833-6a11-4b1a-8d1e-4467db6f24ea.json
Labels: netlify-cms/pending_publish

#4354 Update Exercise “654551b4-1226-485e-9424-4d86d93240ff”
  content/src/exercises/654551b4-1226-485e-9424-4d86d93240ff.json
Labels: netlify-cms/pending_publish

#4355 Update Exercise “9a4834e6-8d3f-420b-88e3-dd3df9a98001”
  content/src/exercises/9a4834e6-8d3f-420b-88e3-dd3df9a98001.json
Labels: netlify-cms/pending_publish

#4357 Update Exercise “c0e6d8d2-163a-4c2d-a0af-250eef846054”
  content/src/exercises/c0e6d8d2-163a-4c2d-a0af-250eef846054.json
Labels: netlify-cms/pending_publish

#4353 Update ⚙️ Settings “exercise-defaults”
  cms/src/defaults/exercise.json
Labels: netlify-cms/pending_publish

#4356 Update Exercise “db239a42-135a-4941-bdf2-92d58107094a”
  content/src/exercises/db239a42-135a-4941-bdf2-92d58107094a.json
Labels: netlify-cms/pending_publish

#4352 Update ⚙️ Settings “text-templates”
  cms/src/templates/editorTexts.json
Labels: netlify-cms/pending_publish

#4359 Update Collection “be8d8f71-1b30-4f9a-80cb-616ff24e8db9”
  content/src/collections/be8d8f71-1b30-4f9a-80cb-616ff24e8db9.json
Labels: netlify-cms/pending_publish

#4362 Update Exercise “654551b4-1226-485e-9424-4d86d93240ff”
  content/src/exercises/654551b4-1226-485e-9424-4d86d93240ff.json
Labels: netlify-cms/pending_publish

#4363 Update Exercise “9a4834e6-8d3f-420b-88e3-dd3df9a98001”
  content/src/exercises/9a4834e6-8d3f-420b-88e3-dd3df9a98001.json
Labels: netlify-cms/pending_publish

#4364 Update Exercise “c0e6d8d2-163a-4c2d-a0af-250eef846054”
  content/src/exercises/c0e6d8d2-163a-4c2d-a0af-250eef846054.json
Labels: netlify-cms/pending_publish

#4365 Update Exercise “0d4c9833-6a11-4b1a-8d1e-4467db6f24ea”
  content/src/exercises/0d4c9833-6a11-4b1a-8d1e-4467db6f24ea.json
Labels: netlify-cms/pending_publish

#4366 Update Exercise “db239a42-135a-4941-bdf2-92d58107094a”
  content/src/exercises/db239a42-135a-4941-bdf2-92d58107094a.json
Labels: netlify-cms/pending_publish

#4367 Update Collection “be8d8f71-1b30-4f9a-80cb-616ff24e8db9”
  content/src/collections/be8d8f71-1b30-4f9a-80cb-616ff24e8db9.json
Labels: netlify-cms/pending_publish

#4415 Add map to today tab
  client/src/assets/animations/today-map.json
  client/src/routes/screens/Home/Home.tsx
  client/yarn.lock
  content/src/ui/Screen.Home.json
Labels: native release

#4411 Update Collection “0eda04e3-4b45-44d6-b779-7b40f43f966c”
  content/src/collections/0eda04e3-4b45-44d6-b779-7b40f43f966c.json
Labels: netlify-cms/pending_publish

#4412 Update Collection “1d35e981-4b8e-47f0-887a-0c90d21fb991”
  content/src/collections/1d35e981-4b8e-47f0-887a-0c90d21fb991.json
Labels: netlify-cms/pending_publish

#4419 Update Collection “68172f5c-955a-43e0-9cef-ae3bc77c9593”
  content/src/collections/68172f5c-955a-43e0-9cef-ae3bc77c9593.json
Labels: netlify-cms/pending_publish

#4418 Update Collection “8cb72f0d-3aad-4fe6-bf08-560b108bb439”
  content/src/collections/8cb72f0d-3aad-4fe6-bf08-560b108bb439.json
Labels: netlify-cms/pending_publish

#4417 Update Collection “1d35e981-4b8e-47f0-887a-0c90d21fb991”
  content/src/collections/1d35e981-4b8e-47f0-887a-0c90d21fb991.json
Labels: netlify-cms/pending_publish

#4420 Update 📱 UI “Component.Tabs”
  content/src/ui/Component.Tabs.json
Labels: netlify-cms/pending_publish

#4425 Update Exercise “095f9642-73b6-4c9a-ae9a-ea7dea7363f5”
  content/src/exercises/095f9642-73b6-4c9a-ae9a-ea7dea7363f5.json
Labels: decap-cms/pending_publish

#4427 Update Category “07c58365-832b-4b3f-b926-c09682632441”
  content/src/categories/07c58365-832b-4b3f-b926-c09682632441.json
Labels: decap-cms/pending_publish

#4429 Update Category “b7257c0a-f180-405f-8aff-05f9f75bddbd”
  content/src/categories/b7257c0a-f180-405f-8aff-05f9f75bddbd.json
Labels: decap-cms/pending_publish

#4430 Update Category “e2d46c10-77c3-4784-a9ea-4e7b4939711d”
  content/src/categories/e2d46c10-77c3-4784-a9ea-4e7b4939711d.json
Labels: decap-cms/pending_publish

#4428 Update Category “4fba05de-cc63-4613-9c84-a34f4cbbc58e”
  content/src/categories/4fba05de-cc63-4613-9c84-a34f4cbbc58e.json
Labels: decap-cms/pending_publish

#4426 Update Exercise “1a53e633-6916-4fea-a072-977c4b215288”
  content/src/exercises/1a53e633-6916-4fea-a072-977c4b215288.json
Labels: decap-cms/pending_publish

#4414 🚢 Release 2.43.0
  client/android/app/build.gradle
  client/ios/Supporting/Info.plist
  client/ios/twentyninek.xcodeproj/project.pbxproj
  client/src/assets/animations/today-map.json
  client/src/routes/screens/Home/Home.tsx
  client/yarn.lock
  content/src/ui/Screen.Home.json
Labels: native release

#4434 Update Exercise “1a53e633-6916-4fea-a072-977c4b215288”
  content/src/exercises/1a53e633-6916-4fea-a072-977c4b215288.json
Labels: decap-cms/pending_publish

#4435 Update Exercise “1a53e633-6916-4fea-a072-977c4b215288”
  content/src/exercises/1a53e633-6916-4fea-a072-977c4b215288.json
Labels: decap-cms/draft

#4438 Update Exercise “9a4834e6-8d3f-420b-88e3-dd3df9a98001”
  content/src/exercises/9a4834e6-8d3f-420b-88e3-dd3df9a98001.json
Labels: decap-cms/draft

#4442 Update Collection “be8d8f71-1b30-4f9a-80cb-616ff24e8db9”
  content/src/collections/be8d8f71-1b30-4f9a-80cb-616ff24e8db9.json
Labels: decap-cms/draft

#4441 Update Exercise “db239a42-135a-4941-bdf2-92d58107094a”
  content/src/exercises/db239a42-135a-4941-bdf2-92d58107094a.json
Labels: decap-cms/draft

#4440 Update Exercise “c0e6d8d2-163a-4c2d-a0af-250eef846054”
  content/src/exercises/c0e6d8d2-163a-4c2d-a0af-250eef846054.json
Labels: decap-cms/draft

#4437 Update Exercise “654551b4-1226-485e-9424-4d86d93240ff”
  content/src/exercises/654551b4-1226-485e-9424-4d86d93240ff.json
Labels: decap-cms/draft

#4436 Update Exercise “0d4c9833-6a11-4b1a-8d1e-4467db6f24ea”
  content/src/exercises/0d4c9833-6a11-4b1a-8d1e-4467db6f24ea.json
Labels: decap-cms/draft

#4443 Update Exercise “648e1802-eb45-47b0-a42e-dd986669a4eb”
  content/src/exercises/648e1802-eb45-47b0-a42e-dd986669a4eb.json
Labels: decap-cms/pending_publish

#4439 Update Exercise “095f9642-73b6-4c9a-ae9a-ea7dea7363f5”
  content/src/exercises/095f9642-73b6-4c9a-ae9a-ea7dea7363f5.json
Labels: decap-cms/pending_publish

#4445 Update Exercise “185889ec-753b-4e2c-8322-3004013e8a6e”
  content/src/exercises/185889ec-753b-4e2c-8322-3004013e8a6e.json
Labels: decap-cms/pending_publish

#4444 Update Exercise “648e1802-eb45-47b0-a42e-dd986669a4eb”
  content/src/exercises/648e1802-eb45-47b0-a42e-dd986669a4eb.json
Labels: decap-cms/pending_publish

#4447 Update Exercise “095f9642-73b6-4c9a-ae9a-ea7dea7363f5”
  content/src/exercises/095f9642-73b6-4c9a-ae9a-ea7dea7363f5.json
Labels: decap-cms/pending_publish

#4478 Create Exercise “b3cf842d-ccb3-4f37-b31f-06f8d14fc775”
  content/src/exercises/b3cf842d-ccb3-4f37-b31f-06f8d14fc775.json
Labels: decap-cms/pending_publish

#4482 Update Exercise “b3cf842d-ccb3-4f37-b31f-06f8d14fc775”
  content/src/exercises/b3cf842d-ccb3-4f37-b31f-06f8d14fc775.json
Labels: decap-cms/pending_publish

#4483 Create Exercise “df2c5312-c869-4ab7-8ac1-1875a04e2229”
  content/src/exercises/df2c5312-c869-4ab7-8ac1-1875a04e2229.json
Labels: decap-cms/pending_publish
