Repository 29ki/29k, pull requests merged in 2024-10, with the labels that each got.

#5919 Update Exercise “e4bf8d17-a774-4702-abfe-c7452c3fee0f”
  content/src/exercises/e4bf8d17-a774-4702-abfe-c7452c3fee0f.json
Labels: decap-cms/pending_publish

#5920 Update Exercise “c0e6d8d2-163a-4c2d-a0af-250eef846054”
  content/src/exercises/c0e6d8d2-163a-4c2d-a0af-250eef846054.json
Labels: decap-cms/pending_publish

#5975 Update Exercise “2d096e25-3f0b-48da-8557-3db607b98ef8”
  content/src/exercises/2d096e25-3f0b-48da-8557-3db607b98ef8.json
Labels: decap-cms/pending_publish

#5977 Update Exercise “742b9b7e-1d2b-43bb-a58b-dd71c5eb5d7a”
  content/src/exercises/742b9b7e-1d2b-43bb-a58b-dd71c5eb5d7a.json
Labels: decap-cms/pending_publish

#5922 Update Exercise “f59b7f66-43b0-4b50-9afe-91092d7dc469”
  content/src/exercises/f59b7f66-43b0-4b50-9afe-91092d7dc469.json
Labels: decap-cms/pending_publish

#5940 Update Exercise “12f448d2-39bc-4232-b8cf-b6cb570c7e00”
  content/src/exercises/12f448d2-39bc-4232-b8cf-b6cb570c7e00.json
Labels: decap-cms/pending_publish

#5924 Update Exercise “640e4d9f-bb88-44af-a032-116a82f080f6”
  content/src/exercises/640e4d9f-bb88-44af-a032-116a82f080f6.json
Labels: decap-cms/pending_publish

#5923 Update Exercise “654551b4-1226-485e-9424-4d86d93240ff”
  content/src/exercises/654551b4-1226-485e-9424-4d86d93240ff.json
Labels: decap-cms/pending_publish

#5939 Update Exercise “b7f8731c-64d7-4c0f-9bc8-a3e50ec2eaf7”
  content/src/exercises/b7f8731c-64d7-4c0f-9bc8-a3e50ec2eaf7.json
Labels: decap-cms/pending_publish

#5921 Update Exercise “c7911238-ca9f-4499-9cae-63dfcd0c79c5”
  content/src/exercises/c7911238-ca9f-4499-9cae-63dfcd0c79c5.json
Labels: decap-cms/pending_publish

#5944 Update Exercise “f4f8a536-5683-40a3-a139-5e3031687cec”
  content/src/exercises/f4f8a536-5683-40a3-a139-5e3031687cec.json
Labels: decap-cms/pending_publish

#5930 Update Exercise “db239a42-135a-4941-bdf2-92d58107094a”
  content/src/exercises/db239a42-135a-4941-bdf2-92d58107094a.json
Labels: decap-cms/pending_publish

#5942 Update Exercise “5b69ff57-10c4-4288-afc7-a6f6ed212531”
  content/src/exercises/5b69ff57-10c4-4288-afc7-a6f6ed212531.json
Labels: decap-cms/pending_publish

#5987 Update Exercise “df2c5312-c869-4ab7-8ac1-1875a04e2229”
  content/src/exercises/df2c5312-c869-4ab7-8ac1-1875a04e2229.json
Labels: decap-cms/pending_publish

#5981 Update Exercise “13dfd5b5-f0af-4783-9fe1-3ba7773bcb89”
  content/src/exercises/13dfd5b5-f0af-4783-9fe1-3ba7773bcb89.json
Labels: decap-cms/pending_publish

#5988 Update Exercise “648e1802-eb45-47b0-a42e-dd986669a4eb”
  content/src/exercises/648e1802-eb45-47b0-a42e-dd986669a4eb.json
Labels: decap-cms/pending_publish

#5982 Update Exercise “9a4834e6-8d3f-420b-88e3-dd3df9a98001”
  content/src/exercises/9a4834e6-8d3f-420b-88e3-dd3df9a98001.json
Labels: decap-cms/pending_publish

#5991 Update Exercise “fff6f8da-f69c-458f-8905-acee04bd1a1d”
  content/src/exercises/fff6f8da-f69c-458f-8905-acee04bd1a1d.json
Labels: decap-cms/pending_publish

#5990 Update Exercise “33a188a2-6871-47d6-a754-f5c246bd6b9a”
  content/src/exercises/33a188a2-6871-47d6-a754-f5c246bd6b9a.json
Labels: decap-cms/pending_publish

#5985 Update Exercise “b1e6cc8e-03a4-4f74-8884-2896c391ab07”
  content/src/exercises/b1e6cc8e-03a4-4f74-8884-2896c391ab07.json
Labels: decap-cms/pending_publish

#5983 Update Exercise “0d4c9833-6a11-4b1a-8d1e-4467db6f24ea”
  content/src/exercises/0d4c9833-6a11-4b1a-8d1e-4467db6f24ea.json
Labels: decap-cms/pending_publish

#5986 Update Exercise “61adeaf2-70ab-4c6c-854c-2c16f762a3c5”
  content/src/exercises/61adeaf2-70ab-4c6c-854c-2c16f762a3c5.json
Labels: decap-cms/pending_publish

#5980 Update Exercise “c4b1c360-88b8-4e05-915a-407e00aef898”
  content/src/exercises/c4b1c360-88b8-4e05-915a-407e00aef898.json
Labels: decap-cms/pending_publish

#5989 Update Exercise “b4307d0b-512d-46d6-a500-7fb372bfe057”
  content/src/exercises/b4307d0b-512d-46d6-a500-7fb372bfe057.json
Labels: decap-cms/pending_publish

#6005 Update Collection “d9897547-18a2-4404-b12b-324458021783”
  content/src/collections/d9897547-18a2-4404-b12b-324458021783.json
Labels: decap-cms/pending_publish

#5997 Update Collection “68172f5c-955a-43e0-9cef-ae3bc77c9593”
  content/src/collections/68172f5c-955a-43e0-9cef-ae3bc77c9593.json
Labels: decap-cms/pending_publish

#5995 Update Collection “36603867-7f45-4f66-8065-2d9b6eb26d0e”
  content/src/collections/36603867-7f45-4f66-8065-2d9b6eb26d0e.json
Labels: decap-cms/pending_publish

#5999 Update Collection “74c65a83-449f-4ff1-97e1-e6f3c443e40b”
  content/src/collections/74c65a83-449f-4ff1-97e1-e6f3c443e40b.json
Labels: decap-cms/pending_publish

#6004 Update Collection “be8d8f71-1b30-4f9a-80cb-616ff24e8db9”
  content/src/collections/be8d8f71-1b30-4f9a-80cb-616ff24e8db9.json
Labels: decap-cms/pending_publish

#5998 Update Collection “716c2b31-612c-40c4-8e85-90f0a2af380e”
  content/src/collections/716c2b31-612c-40c4-8e85-90f0a2af380e.json
Labels: decap-cms/pending_publish

#6003 Update Collection “b77e52b5-c927-4178-ba76-8c3fe3dbf13c”
  content/src/collections/b77e52b5-c927-4178-ba76-8c3fe3dbf13c.json
Labels: decap-cms/pending_publish

#6001 Update Collection “9739d765-08e4-401c-88e9-3318e75ce41a”
  content/src/collections/9739d765-08e4-401c-88e9-3318e75ce41a.json
Labels: decap-cms/pending_publish

#6000 Update Collection “8cb72f0d-3aad-4fe6-bf08-560b108bb439”
  content/src/collections/8cb72f0d-3aad-4fe6-bf08-560b108bb439.json
Labels: decap-cms/pending_publish

#5993 Update Collection “0eda04e3-4b45-44d6-b779-7b40f43f966c”
  content/src/collections/0eda04e3-4b45-44d6-b779-7b40f43f966c.json
Labels: decap-cms/pending_publish

#5992 Update Exercise “c1c4da35-87af-4e10-a8d9-e6c58571f724”
  content/src/exercises/c1c4da35-87af-4e10-a8d9-e6c58571f724.json
Labels: decap-cms/pending_publish

#6006 Update Collection “dcb02b73-c515-44a1-bee3-850dbd5eb2a1”
  content/src/collections/dcb02b73-c515-44a1-bee3-850dbd5eb2a1.json
Labels: decap-cms/pending_publish

#5994 Update Collection “1d35e981-4b8e-47f0-887a-0c90d21fb991”
  content/src/collections/1d35e981-4b8e-47f0-887a-0c90d21fb991.json
Labels: decap-cms/pending_publish

#6008 Update Category “4fba05de-cc63-4613-9c84-a34f4cbbc58e”
  content/src/categories/4fba05de-cc63-4613-9c84-a34f4cbbc58e.json
Labels: decap-cms/pending_publish

#6009 Update Category “b7257c0a-f180-405f-8aff-05f9f75bddbd”
  content/src/categories/b7257c0a-f180-405f-8aff-05f9f75bddbd.json
Labels: decap-cms/pending_publish

#6010 Update Category “e2d46c10-77c3-4784-a9ea-4e7b4939711d”
  content/src/categories/e2d46c10-77c3-4784-a9ea-4e7b4939711d.json
Labels: decap-cms/pending_publish

#6007 Update Category “07c58365-832b-4b3f-b926-c09682632441”
  content/src/categories/07c58365-832b-4b3f-b926-c09682632441.json
Labels: decap-cms/pending_publish

#6013 Update 📱 UI “Modal.Contact”
  content/src/ui/Modal.Contact.json
Labels: decap-cms/pending_publish

#6019 Update 📱 UI “Screen.Collection”
  content/src/ui/Screen.Collection.json
Labels: decap-cms/pending_publish

#6020 Update 📱 UI “Screen.Explore”
  content/src/ui/Screen.Explore.json
Labels: decap-cms/pending_publish

#6016 Update 📱 UI “Modal.SessionError”
  content/src/ui/Modal.SessionError.json
Labels: decap-cms/pending_publish

#6011 Update 📱 UI “Component.PostRelates”
  content/src/ui/Component.PostRelates.json
Labels: decap-cms/pending_publish

#6012 Update 📱 UI “Modal.AddSession”
  content/src/ui/Modal.AddSession.json
Labels: decap-cms/pending_publish

#6018 Update 📱 UI “Overlay.AboutEditorial”
  content/src/ui/Overlay.AboutEditorial.json
Labels: decap-cms/pending_publish

#6014 Update 📱 UI “Modal.CreateSession”
  content/src/ui/Modal.CreateSession.json
Labels: decap-cms/pending_publish

#6022 Update Collection “7bb77b5d-7a97-4fd1-9102-21eb0c4a70af”
  content/src/collections/7bb77b5d-7a97-4fd1-9102-21eb0c4a70af.json
Labels: decap-cms/pending_publish

#6023 Update Collection “7bb77b5d-7a97-4fd1-9102-21eb0c4a70af”
  content/src/collections/7bb77b5d-7a97-4fd1-9102-21eb0c4a70af.json
Labels: decap-cms/pending_publish

#5761 🚢 Release 2.57.0
  client/android/app/build.gradle
  client/ios/Podfile.lock
  client/ios/Supporting/Info.plist
  client/ios/twentyninek.xcodeproj/project.pbxproj
  client/package.json
  client/yarn.lock
Labels: native release

#6025 Update Exercise “c7911238-ca9f-4499-9cae-63dfcd0c79c5”
  content/src/exercises/c7911238-ca9f-4499-9cae-63dfcd0c79c5.json
Labels: decap-cms/pending_publish

#6028 Update Exercise “19573b9a-e2f2-4bba-9687-35d261cbbf49”
  content/src/exercises/19573b9a-e2f2-4bba-9687-35d261cbbf49.json
Labels: decap-cms/pending_publish

#6057 Update Exercise “b9001702-8502-46de-bc7b-3ebf2b812c0e”
  content/src/exercises/b9001702-8502-46de-bc7b-3ebf2b812c0e.json
Labels: decap-cms/pending_publish

#6058 Update Exercise “3adeb40b-b9f8-4b13-b1a8-02f6106df9e5”
  content/src/exercises/3adeb40b-b9f8-4b13-b1a8-02f6106df9e5.json
Labels: decap-cms/pending_publish

#6061 Update 📱 UI “Component.TimerControls”
  content/src/ui/Component.TimerControls.json
Labels: decap-cms/pending_publish

#6063 Update Exercise “961656ea-021c-4faa-ae03-46d6ace4be4b”
  content/src/exercises/961656ea-021c-4faa-ae03-46d6ace4be4b.json
Labels: decap-cms/pending_publish

#6064 Update Exercise “94575e97-fe03-4bfd-94a6-50aaf721d47e”
  content/src/exercises/94575e97-fe03-4bfd-94a6-50aaf721d47e.json
Labels: decap-cms/pending_publish

#6067 Update Exercise “3188a5ed-a1d6-451c-ae2a-f44f4df37495”
  content/src/exercises/3188a5ed-a1d6-451c-ae2a-f44f4df37495.json
Labels: decap-cms/pending_publish

#6066 Update Exercise “095f9642-73b6-4c9a-ae9a-ea7dea7363f5”
  content/src/exercises/095f9642-73b6-4c9a-ae9a-ea7dea7363f5.json
Labels: decap-cms/pending_publish

#6065 Update Exercise “b18c1cff-bb43-44b1-81a1-2877cc018ab4”
  content/src/exercises/b18c1cff-bb43-44b1-81a1-2877cc018ab4.json
Labels: decap-cms/pending_publish

#6068 Update Exercise “2fdb95f0-d18d-444d-9935-2c71b9b413d4”
  content/src/exercises/2fdb95f0-d18d-444d-9935-2c71b9b413d4.json
Labels: decap-cms/pending_publish

#6069 Update Exercise “ea0b48c1-745e-418d-93e7-2d8a6cd72898”
  content/src/exercises/ea0b48c1-745e-418d-93e7-2d8a6cd72898.json
Labels: decap-cms/pending_publish

#6070 Update Exercise “185889ec-753b-4e2c-8322-3004013e8a6e”
  content/src/exercises/185889ec-753b-4e2c-8322-3004013e8a6e.json
Labels: decap-cms/pending_publish

#6071 Update Exercise “185889ec-753b-4e2c-8322-3004013e8a6e”
  content/src/exercises/185889ec-753b-4e2c-8322-3004013e8a6e.json
Labels: decap-cms/pending_publish

#6093 Update Collection “0eda04e3-4b45-44d6-b779-7b40f43f966c”
  content/src/collections/0eda04e3-4b45-44d6-b779-7b40f43f966c.json
Labels: decap-cms/pending_publish

#6094 Update Exercise “c5b1197a-4eec-4699-9dad-0e3d6323967b”
  content/src/exercises/c5b1197a-4eec-4699-9dad-0e3d6323967b.json
Labels: decap-cms/pending_publish

#6137 Update 📱 UI “Screen.Onboarding”
  content/src/ui/Screen.Onboarding.json
Labels: decap-cms/draft

#6139 Update Exercise “94575e97-fe03-4bfd-94a6-50aaf721d47e”
  content/src/exercises/94575e97-fe03-4bfd-94a6-50aaf721d47e.json
Labels: decap-cms/pending_publish

#6154 Update Exercise “a0600ebe-748d-481c-81af-dab25fa32b76”
  content/src/exercises/a0600ebe-748d-481c-81af-dab25fa32b76.json
Labels: decap-cms/pending_publish

#6152 Update Exercise “1a53e633-6916-4fea-a072-977c4b215288”
  content/src/exercises/1a53e633-6916-4fea-a072-977c4b215288.json
Labels: decap-cms/pending_publish

#6142 Update Exercise “ea0b48c1-745e-418d-93e7-2d8a6cd72898”
  content/src/exercises/ea0b48c1-745e-418d-93e7-2d8a6cd72898.json
Labels: decap-cms/pending_publish

#6162 Update Exercise “df2c5312-c869-4ab7-8ac1-1875a04e2229”
  content/src/exercises/df2c5312-c869-4ab7-8ac1-1875a04e2229.json
Labels: decap-cms/pending_publish

#6161 Update Exercise “3f4710a6-1fc9-45c3-b636-d18f31a2d751”
  content/src/exercises/3f4710a6-1fc9-45c3-b636-d18f31a2d751.json
Labels: decap-cms/pending_publish

#6144 Update Exercise “13dfd5b5-f0af-4783-9fe1-3ba7773bcb89”
  content/src/exercises/13dfd5b5-f0af-4783-9fe1-3ba7773bcb89.json
Labels: decap-cms/pending_publish

#6163 Update Exercise “648e1802-eb45-47b0-a42e-dd986669a4eb”
  content/src/exercises/648e1802-eb45-47b0-a42e-dd986669a4eb.json
Labels: decap-cms/pending_publish

#6153 Update Exercise “2fdb95f0-d18d-444d-9935-2c71b9b413d4”
  content/src/exercises/2fdb95f0-d18d-444d-9935-2c71b9b413d4.json
Labels: decap-cms/pending_publish

#6166 Update Exercise “12f448d2-39bc-4232-b8cf-b6cb570c7e00”
  content/src/exercises/12f448d2-39bc-4232-b8cf-b6cb570c7e00.json
Labels: decap-cms/pending_publish

#6143 Update Exercise “ab3c3bc4-5586-4554-aa93-ebe7d6910741”
  content/src/exercises/ab3c3bc4-5586-4554-aa93-ebe7d6910741.json
Labels: decap-cms/pending_publish

#6145 Update Exercise “9a4834e6-8d3f-420b-88e3-dd3df9a98001”
  content/src/exercises/9a4834e6-8d3f-420b-88e3-dd3df9a98001.json
Labels: decap-cms/pending_publish

#6158 Update Exercise “19135d2e-0e8d-418c-939d-18b0e62215ff”
  content/src/exercises/19135d2e-0e8d-418c-939d-18b0e62215ff.json
Labels: decap-cms/pending_publish

#6160 Update Exercise “095f9642-73b6-4c9a-ae9a-ea7dea7363f5”
  content/src/exercises/095f9642-73b6-4c9a-ae9a-ea7dea7363f5.json
Labels: decap-cms/pending_publish

#6157 Update Exercise “b1e6cc8e-03a4-4f74-8884-2896c391ab07”
  content/src/exercises/b1e6cc8e-03a4-4f74-8884-2896c391ab07.json
Labels: decap-cms/pending_publish

#6150 Update Exercise “640e4d9f-bb88-44af-a032-116a82f080f6”
  content/src/exercises/640e4d9f-bb88-44af-a032-116a82f080f6.json
Labels: decap-cms/pending_publish

#6147 Update Exercise “654551b4-1226-485e-9424-4d86d93240ff”
  content/src/exercises/654551b4-1226-485e-9424-4d86d93240ff.json
Labels: decap-cms/pending_publish

#6155 Update Exercise “2ea0d73d-4bfe-4e23-9124-2998acc9743f”
  content/src/exercises/2ea0d73d-4bfe-4e23-9124-2998acc9743f.json
Labels: decap-cms/pending_publish

#6148 Update Exercise “0d4c9833-6a11-4b1a-8d1e-4467db6f24ea”
  content/src/exercises/0d4c9833-6a11-4b1a-8d1e-4467db6f24ea.json
Labels: decap-cms/pending_publish

#6159 Update Exercise “61adeaf2-70ab-4c6c-854c-2c16f762a3c5”
  content/src/exercises/61adeaf2-70ab-4c6c-854c-2c16f762a3c5.json
Labels: decap-cms/pending_publish

#6165 Update Exercise “c5b1197a-4eec-4699-9dad-0e3d6323967b”
  content/src/exercises/c5b1197a-4eec-4699-9dad-0e3d6323967b.json
Labels: decap-cms/pending_publish

#6149 Update Exercise “e4bf8d17-a774-4702-abfe-c7452c3fee0f”
  content/src/exercises/e4bf8d17-a774-4702-abfe-c7452c3fee0f.json
Labels: decap-cms/pending_publish

#6138 Update Exercise “c0e6d8d2-163a-4c2d-a0af-250eef846054”
  content/src/exercises/c0e6d8d2-163a-4c2d-a0af-250eef846054.json
Labels: decap-cms/pending_publish

#6151 Update Exercise “db239a42-135a-4941-bdf2-92d58107094a”
  content/src/exercises/db239a42-135a-4941-bdf2-92d58107094a.json
Labels: decap-cms/pending_publish

#6164 Update Exercise “b4307d0b-512d-46d6-a500-7fb372bfe057”
  content/src/exercises/b4307d0b-512d-46d6-a500-7fb372bfe057.json
Labels: decap-cms/pending_publish

#6168 Update Exercise “185889ec-753b-4e2c-8322-3004013e8a6e”
  content/src/exercises/185889ec-753b-4e2c-8322-3004013e8a6e.json
Labels: decap-cms/pending_publish

#6169 Update Exercise “fff6f8da-f69c-458f-8905-acee04bd1a1d”
  content/src/exercises/fff6f8da-f69c-458f-8905-acee04bd1a1d.json
Labels: decap-cms/pending_publish

#6172 Update Exercise “9ac0c561-ff26-45fc-b6d5-0a983432394e”
  content/src/exercises/9ac0c561-ff26-45fc-b6d5-0a983432394e.json
Labels: decap-cms/pending_publish

#6170 Update Exercise “3188a5ed-a1d6-451c-ae2a-f44f4df37495”
  content/src/exercises/3188a5ed-a1d6-451c-ae2a-f44f4df37495.json
Labels: decap-cms/pending_publish

#6175 Update Exercise “f4f8a536-5683-40a3-a139-5e3031687cec”
  content/src/exercises/f4f8a536-5683-40a3-a139-5e3031687cec.json
Labels: decap-cms/pending_publish

#6173 Update Exercise “961656ea-021c-4faa-ae03-46d6ace4be4b”
  content/src/exercises/961656ea-021c-4faa-ae03-46d6ace4be4b.json
Labels: decap-cms/pending_publish

#6177 Update Exercise “2d096e25-3f0b-48da-8557-3db607b98ef8”
  content/src/exercises/2d096e25-3f0b-48da-8557-3db607b98ef8.json
Labels: decap-cms/pending_publish

#6176 Update Exercise “0bcb6eb0-fdfe-466d-8603-ae6de15fcbc5”
  content/src/exercises/0bcb6eb0-fdfe-466d-8603-ae6de15fcbc5.json
Labels: decap-cms/pending_publish

#6178 Update Exercise “c1c4da35-87af-4e10-a8d9-e6c58571f724”
  content/src/exercises/c1c4da35-87af-4e10-a8d9-e6c58571f724.json
Labels: decap-cms/pending_publish
