Repository 29ki/29k, pull requests merged in 2024-05, with the labels that each got.

#5249 Update 📱 UI “Screen.Onboarding”
  content/src/ui/Screen.Onboarding.json
Labels: decap-cms/pending_publish

#5250 Update 📱 UI “Screen.Collection”
  content/src/ui/Screen.Collection.json
Labels: decap-cms/pending_publish

#5251 Update 📱 UI “Screen.Explore”
  content/src/ui/Screen.Explore.json
Labels: decap-cms/pending_publish

#5253 Update 📱 UI “Screen.Onboarding”
  content/src/ui/Screen.Onboarding.json
Labels: decap-cms/pending_publish

#5264 Update 📱 UI “Screen.Onboarding”
  content/src/ui/Screen.Onboarding.json
Labels: decap-cms/pending_publish

#5265 Update 📱 UI “Screen.Onboarding”
  content/src/ui/Screen.Onboarding.json
Labels: decap-cms/pending_publish

#5272 Update 📱 UI “Component.ConfirmLogMindfulMinutes”
  content/src/ui/Component.ConfirmLogMindfulMinutes.json
Labels: decap-cms/pending_publish

#5275 Update 📱 UI “Component.NetworkError”
  content/src/ui/Component.NetworkError.json
Labels: decap-cms/pending_publish

#5276 Update 📱 UI “Component.NotificationChannels”
  content/src/ui/Component.NotificationChannels.json
Labels: decap-cms/pending_publish

#5283 Update 📱 UI “Component.SignOut”
  content/src/ui/Component.SignOut.json
Labels: decap-cms/pending_publish

#5277 Update 📱 UI “Component.Participant”
  content/src/ui/Component.Participant.json
Labels: decap-cms/pending_publish

#5284 Update 📱 UI “DeepLink.HostSessionInvite”
  content/src/ui/DeepLink.HostSessionInvite.json
Labels: decap-cms/pending_publish

#5271 Update 📱 UI “Component.Collection”
  content/src/ui/Component.Collection.json
Labels: decap-cms/pending_publish

#5269 Update 📱 UI “Component.AddToCalendar”
  content/src/ui/Component.AddToCalendar.json
Labels: decap-cms/pending_publish

#5278 Update 📱 UI “Component.RequestCalendarPermission”
  content/src/ui/Component.RequestCalendarPermission.json
Labels: decap-cms/pending_publish

#5273 Update 📱 UI “Component.ConfirmPracticeReminders”
  content/src/ui/Component.ConfirmPracticeReminders.json
Labels: decap-cms/pending_publish

#5281 Update 📱 UI “Component.Sharing”
  content/src/ui/Component.Sharing.json
Labels: decap-cms/pending_publish

#5274 Update 📱 UI “Component.CrashErrorMessage”
  content/src/ui/Component.CrashErrorMessage.json
Labels: decap-cms/pending_publish

#5282 Update 📱 UI “Component.SharingSessionMood”
  content/src/ui/Component.SharingSessionMood.json
Labels: decap-cms/pending_publish

#5304 Update 📱 UI “Modal.SessionFeedback”
  content/src/ui/Modal.SessionFeedback.json
Labels: decap-cms/pending_publish

#5305 Update 📱 UI “Modal.Sharing”
  content/src/ui/Modal.Sharing.json
Labels: decap-cms/pending_publish

#5306 Update 📱 UI “Modal.SharingPost”
  content/src/ui/Modal.SharingPost.json
Labels: decap-cms/pending_publish

#5298 Update 📱 UI “Modal.HowItWorks”
  content/src/ui/Modal.HowItWorks.json
Labels: decap-cms/pending_publish

#5316 Update 📱 UI “Screen.Onboarding”
  content/src/ui/Screen.Onboarding.json
Labels: decap-cms/pending_publish

#5299 Update 📱 UI “Modal.LiveSessions”
  content/src/ui/Modal.LiveSessions.json
Labels: decap-cms/pending_publish

#5296 Update 📱 UI “Modal.HostingInviteFail”
  content/src/ui/Modal.HostingInviteFail.json
Labels: decap-cms/pending_publish

#5313 Update 📱 UI “Screen.Collection”
  content/src/ui/Screen.Collection.json
Labels: decap-cms/pending_publish

#5301 Update 📱 UI “Modal.Reminders”
  content/src/ui/Modal.Reminders.json
Labels: decap-cms/pending_publish

#5287 Update 📱 UI “Modal.CompletedSession”
  content/src/ui/Modal.CompletedSession.json
Labels: decap-cms/pending_publish

#5315 Update 📱 UI “Screen.Home”
  content/src/ui/Screen.Home.json
Labels: decap-cms/pending_publish

#5286 Update 📱 UI “DeepLink.HostSessionInvite”
  content/src/ui/DeepLink.HostSessionInvite.json
Labels: decap-cms/pending_publish

#5291 Update 📱 UI “Modal.Donate”
  content/src/ui/Modal.Donate.json
Labels: decap-cms/pending_publish

#5314 Update 📱 UI “Screen.Explore”
  content/src/ui/Screen.Explore.json
Labels: decap-cms/pending_publish

#5303 Update 📱 UI “Modal.SessionError”
  content/src/ui/Modal.SessionError.json
Labels: decap-cms/pending_publish

#5317 Update 📱 UI “Screen.Session”
  content/src/ui/Screen.Session.json
Labels: decap-cms/pending_publish

#5297 Update 📱 UI “Modal.Hosts”
  content/src/ui/Modal.Hosts.json
Labels: decap-cms/pending_publish

#5312 Update 📱 UI “Screen.ChangingRoom”
  content/src/ui/Screen.ChangingRoom.json
Labels: decap-cms/pending_publish

#5289 Update 📱 UI “Modal.DeleteUser”
  content/src/ui/Modal.DeleteUser.json
Labels: decap-cms/pending_publish

#5294 Update 📱 UI “Modal.HostInfo”
  content/src/ui/Modal.HostInfo.json
Labels: decap-cms/pending_publish

#5300 Update 📱 UI “Modal.ProfileSettings”
  content/src/ui/Modal.ProfileSettings.json
Labels: decap-cms/pending_publish

#5295 Update 📱 UI “Modal.HostSessionByInvite”
  content/src/ui/Modal.HostSessionByInvite.json
Labels: decap-cms/pending_publish

#5310 Update 📱 UI “Notification.PracticeReminder”
  content/src/ui/Notification.PracticeReminder.json
Labels: decap-cms/pending_publish

#5293 Update 📱 UI “Modal.ForgotPassword”
  content/src/ui/Modal.ForgotPassword.json
Labels: decap-cms/pending_publish

#5302 Update 📱 UI “Modal.Session”
  content/src/ui/Modal.Session.json
Labels: decap-cms/pending_publish

#5309 Update 📱 UI “Modal.UnlockCollection”
  content/src/ui/Modal.UnlockCollection.json
Labels: decap-cms/pending_publish

#5307 Update 📱 UI “Modal.SignIn”
  content/src/ui/Modal.SignIn.json
Labels: decap-cms/pending_publish

#5285 Update 📱 UI “Modal.AssignNewHost”
  content/src/ui/Modal.AssignNewHost.json
Labels: decap-cms/pending_publish

#5292 Update 📱 UI “Modal.EditSessionDate”
  content/src/ui/Modal.EditSessionDate.json
Labels: decap-cms/pending_publish

#5288 Update 📱 UI “Modal.CreateSession”
  content/src/ui/Modal.CreateSession.json
Labels: decap-cms/pending_publish

#5311 Update 📱 UI “Notification.SessionReminder”
  content/src/ui/Notification.SessionReminder.json
Labels: decap-cms/pending_publish

#5308 Update 📱 UI “Modal.SimpleProfileSettings”
  content/src/ui/Modal.SimpleProfileSettings.json
Labels: decap-cms/pending_publish

#5268 Create Exercise “3843d06f-1c38-47b9-ad9b-5a780f364186”
  content/src/exercises/3843d06f-1c38-47b9-ad9b-5a780f364186.json
Labels: decap-cms/pending_publish

#5266 Create Exercise “4dd7b844-b54a-4d00-b867-73d19a9b0729”
  content/src/exercises/4dd7b844-b54a-4d00-b867-73d19a9b0729.json
Labels: decap-cms/pending_publish

#5267 Create Exercise “0e663e57-e320-4ec2-b246-b0a9de3f4056”
  content/src/exercises/0e663e57-e320-4ec2-b246-b0a9de3f4056.json
Labels: decap-cms/pending_publish

#5221 Create Exercise “4ade5d0d-6959-4ba6-9b0c-d98aef65b754”
  content/src/exercises/4ade5d0d-6959-4ba6-9b0c-d98aef65b754.json
Labels: decap-cms/pending_publish

#5324 Create Collection “12c07699-0129-4f9a-aab2-564e45d81484”
  content/src/collections/12c07699-0129-4f9a-aab2-564e45d81484.json
Labels: decap-cms/pending_publish

#5326 Update Collection “12c07699-0129-4f9a-aab2-564e45d81484”
  content/src/collections/12c07699-0129-4f9a-aab2-564e45d81484.json
Labels: decap-cms/pending_publish

#5329 Update Category “b7257c0a-f180-405f-8aff-05f9f75bddbd”
  content/src/categories/b7257c0a-f180-405f-8aff-05f9f75bddbd.json
Labels: decap-cms/pending_publish

#5332 Update Collection “af1c4ac9-1bae-4cb1-8c98-e1f98a8aea66”
  content/src/collections/af1c4ac9-1bae-4cb1-8c98-e1f98a8aea66.json
Labels: decap-cms/pending_publish

#5328 Update Category “4fba05de-cc63-4613-9c84-a34f4cbbc58e”
  content/src/categories/4fba05de-cc63-4613-9c84-a34f4cbbc58e.json
Labels: decap-cms/pending_publish

#5331 Update Collection “8cb72f0d-3aad-4fe6-bf08-560b108bb439”
  content/src/collections/8cb72f0d-3aad-4fe6-bf08-560b108bb439.json
Labels: decap-cms/pending_publish

#5330 Update Category “e2d46c10-77c3-4784-a9ea-4e7b4939711d”
  content/src/categories/e2d46c10-77c3-4784-a9ea-4e7b4939711d.json
Labels: decap-cms/pending_publish

#5327 Update Category “07c58365-832b-4b3f-b926-c09682632441”
  content/src/categories/07c58365-832b-4b3f-b926-c09682632441.json
Labels: decap-cms/pending_publish

#5333 Update Collection “12c07699-0129-4f9a-aab2-564e45d81484”
  content/src/collections/12c07699-0129-4f9a-aab2-564e45d81484.json
Labels: decap-cms/pending_publish

#5334 Update Collection “12c07699-0129-4f9a-aab2-564e45d81484”
  content/src/collections/12c07699-0129-4f9a-aab2-564e45d81484.json
Labels: decap-cms/pending_publish

#5355 Update Exercise “54b9accd-f904-4a0f-b7b6-91948bd2c7c8”
  content/src/exercises/54b9accd-f904-4a0f-b7b6-91948bd2c7c8.json
Labels: decap-cms/pending_publish

#5356 Update Exercise “1e96f73b-8193-4aa6-a52c-31355eac3c08”
  content/src/exercises/1e96f73b-8193-4aa6-a52c-31355eac3c08.json
Labels: decap-cms/pending_publish

#5357 Update Exercise “1e96f73b-8193-4aa6-a52c-31355eac3c08”
  content/src/exercises/1e96f73b-8193-4aa6-a52c-31355eac3c08.json
Labels: decap-cms/pending_publish

#5358 Update Exercise “5b0dea9f-c665-41ce-a779-601d0cfa433d”
  content/src/exercises/5b0dea9f-c665-41ce-a779-601d0cfa433d.json
Labels: decap-cms/pending_publish

#5364 Update Exercise “1e96f73b-8193-4aa6-a52c-31355eac3c08”
  content/src/exercises/1e96f73b-8193-4aa6-a52c-31355eac3c08.json
Labels: decap-cms/pending_publish

#5365 Update Exercise “5b0dea9f-c665-41ce-a779-601d0cfa433d”
  content/src/exercises/5b0dea9f-c665-41ce-a779-601d0cfa433d.json
Labels: decap-cms/pending_publish

#5370 Update Exercise “5b0dea9f-c665-41ce-a779-601d0cfa433d”
  content/src/exercises/5b0dea9f-c665-41ce-a779-601d0cfa433d.json
Labels: decap-cms/pending_publish

#5359 Update Exercise “4ade5d0d-6959-4ba6-9b0c-d98aef65b754”
  content/src/exercises/4ade5d0d-6959-4ba6-9b0c-d98aef65b754.json
Labels: decap-cms/pending_publish

#5361 Update Exercise “0e663e57-e320-4ec2-b246-b0a9de3f4056”
  content/src/exercises/0e663e57-e320-4ec2-b246-b0a9de3f4056.json
Labels: decap-cms/pending_publish

#5360 Update Exercise “4dd7b844-b54a-4d00-b867-73d19a9b0729”
  content/src/exercises/4dd7b844-b54a-4d00-b867-73d19a9b0729.json
Labels: decap-cms/pending_publish

#5362 Update Exercise “3843d06f-1c38-47b9-ad9b-5a780f364186”
  content/src/exercises/3843d06f-1c38-47b9-ad9b-5a780f364186.json
Labels: decap-cms/pending_publish

#5396 Update Exercise “1e96f73b-8193-4aa6-a52c-31355eac3c08”
  content/src/exercises/1e96f73b-8193-4aa6-a52c-31355eac3c08.json
Labels: decap-cms/draft

#5397 Update Exercise “1e96f73b-8193-4aa6-a52c-31355eac3c08”
  content/src/exercises/1e96f73b-8193-4aa6-a52c-31355eac3c08.json
Labels: decap-cms/pending_publish

#5350 🚢 Release 2.53.2
  client/android/app/build.gradle
  client/ios/Podfile.lock
  client/ios/Supporting/Info.plist
  client/ios/Supporting/PrivacyInfo.xcprivacy
  client/ios/twentyninek.xcodeproj/project.pbxproj
  client/package.json
  client/yarn.lock
Labels: native release

#5403 Update Tag “34100e43-2eb8-4d35-8eb0-9fa9f78e4935”
  content/src/tags/34100e43-2eb8-4d35-8eb0-9fa9f78e4935.json
Labels: decap-cms/pending_publish

#5406 Update Tag “8da0534a-5da9-430a-bdf3-242ace6460fb”
  content/src/tags/8da0534a-5da9-430a-bdf3-242ace6460fb.json
Labels: decap-cms/pending_publish

#5405 Update Tag “566aeb1b-1649-4f5a-96a2-0c80be27efc0”
  content/src/tags/566aeb1b-1649-4f5a-96a2-0c80be27efc0.json
Labels: decap-cms/pending_publish

#5404 Update Tag “43a6dc0d-d866-4b79-9453-13c44e906128”
  content/src/tags/43a6dc0d-d866-4b79-9453-13c44e906128.json
Labels: decap-cms/pending_publish

#5408 Update Tag “cfc00217-f65b-4a4d-8b82-8ccc8f852dd6”
  content/src/tags/cfc00217-f65b-4a4d-8b82-8ccc8f852dd6.json
Labels: decap-cms/pending_publish

#5407 Update Tag “9c2c08a9-7dc6-4058-bc78-016d0eb00614”
  content/src/tags/9c2c08a9-7dc6-4058-bc78-016d0eb00614.json
Labels: decap-cms/pending_publish

#5409 Update Tag “db34d82a-4c48-4ddd-9de5-f562d8aa1bc9”
  content/src/tags/db34d82a-4c48-4ddd-9de5-f562d8aa1bc9.json
Labels: decap-cms/pending_publish

#5402 Update Exercise “961656ea-021c-4faa-ae03-46d6ace4be4b”
  content/src/exercises/961656ea-021c-4faa-ae03-46d6ace4be4b.json
Labels: decap-cms/pending_publish

#5410 Update Exercise “961656ea-021c-4faa-ae03-46d6ace4be4b”
  content/src/exercises/961656ea-021c-4faa-ae03-46d6ace4be4b.json
Labels: decap-cms/pending_publish

#5411 Update Exercise “94575e97-fe03-4bfd-94a6-50aaf721d47e”
  content/src/exercises/94575e97-fe03-4bfd-94a6-50aaf721d47e.json
Labels: decap-cms/pending_publish

#5412 Update Exercise “94575e97-fe03-4bfd-94a6-50aaf721d47e”
  content/src/exercises/94575e97-fe03-4bfd-94a6-50aaf721d47e.json
Labels: decap-cms/pending_publish

#5413 Update Exercise “b18c1cff-bb43-44b1-81a1-2877cc018ab4”
  content/src/exercises/b18c1cff-bb43-44b1-81a1-2877cc018ab4.json
Labels: decap-cms/pending_publish

#5414 Update Exercise “9ac0c561-ff26-45fc-b6d5-0a983432394e”
  content/src/exercises/9ac0c561-ff26-45fc-b6d5-0a983432394e.json
Labels: decap-cms/pending_publish

#5417 Update Exercise “a0600ebe-748d-481c-81af-dab25fa32b76”
  content/src/exercises/a0600ebe-748d-481c-81af-dab25fa32b76.json
Labels: decap-cms/pending_publish

#5419 Update Collection “5c71e48d-f2a2-498c-9860-3b617f792416”
  content/src/collections/5c71e48d-f2a2-498c-9860-3b617f792416.json
Labels: decap-cms/pending_publish

#5421 Update Exercise “b18c1cff-bb43-44b1-81a1-2877cc018ab4”
  content/src/exercises/b18c1cff-bb43-44b1-81a1-2877cc018ab4.json
Labels: decap-cms/pending_publish

#5423 Update Exercise “095f9642-73b6-4c9a-ae9a-ea7dea7363f5”
  content/src/exercises/095f9642-73b6-4c9a-ae9a-ea7dea7363f5.json
Labels: decap-cms/pending_publish

#5422 Update Exercise “9ac0c561-ff26-45fc-b6d5-0a983432394e”
  content/src/exercises/9ac0c561-ff26-45fc-b6d5-0a983432394e.json
Labels: decap-cms/pending_publish

#5418 Update Exercise “3188a5ed-a1d6-451c-ae2a-f44f4df37495”
  content/src/exercises/3188a5ed-a1d6-451c-ae2a-f44f4df37495.json
Labels: decap-cms/pending_publish

#5424 Update Exercise “19135d2e-0e8d-418c-939d-18b0e62215ff”
  content/src/exercises/19135d2e-0e8d-418c-939d-18b0e62215ff.json
Labels: decap-cms/pending_publish

#5425 Update Exercise “2ea0d73d-4bfe-4e23-9124-2998acc9743f”
  content/src/exercises/2ea0d73d-4bfe-4e23-9124-2998acc9743f.json
Labels: decap-cms/pending_publish

#5426 Update Exercise “2fdb95f0-d18d-444d-9935-2c71b9b413d4”
  content/src/exercises/2fdb95f0-d18d-444d-9935-2c71b9b413d4.json
Labels: decap-cms/pending_publish

#5427 Update Collection “5c71e48d-f2a2-498c-9860-3b617f792416”
  content/src/collections/5c71e48d-f2a2-498c-9860-3b617f792416.json
Labels: decap-cms/pending_publish

#5428 Update Exercise “a0600ebe-748d-481c-81af-dab25fa32b76”
  content/src/exercises/a0600ebe-748d-481c-81af-dab25fa32b76.json
Labels: decap-cms/pending_publish

#5430 Update Exercise “e4bf8d17-a774-4702-abfe-c7452c3fee0f”
  content/src/exercises/e4bf8d17-a774-4702-abfe-c7452c3fee0f.json
Labels: decap-cms/pending_publish

#5431 Update Exercise “ea0b48c1-745e-418d-93e7-2d8a6cd72898”
  content/src/exercises/ea0b48c1-745e-418d-93e7-2d8a6cd72898.json
Labels: decap-cms/pending_publish

#5432 Create Collection “74c65a83-449f-4ff1-97e1-e6f3c443e40b”
  content/src/collections/74c65a83-449f-4ff1-97e1-e6f3c443e40b.json
Labels: decap-cms/pending_publish

#5433 Update Collection “74c65a83-449f-4ff1-97e1-e6f3c443e40b”
  content/src/collections/74c65a83-449f-4ff1-97e1-e6f3c443e40b.json
Labels: decap-cms/pending_publish

#5366 Create Exercise “0db526a6-9f70-4cf8-8903-71feb68413c1”
  content/src/exercises/0db526a6-9f70-4cf8-8903-71feb68413c1.json
Labels: decap-cms/pending_publish

#5464 Update Exercise “3843d06f-1c38-47b9-ad9b-5a780f364186”
  content/src/exercises/3843d06f-1c38-47b9-ad9b-5a780f364186.json
Labels: decap-cms/pending_publish

#5461 Update Exercise “4dd7b844-b54a-4d00-b867-73d19a9b0729”
  content/src/exercises/4dd7b844-b54a-4d00-b867-73d19a9b0729.json
Labels: decap-cms/pending_publish

#5463 Update Exercise “0e663e57-e320-4ec2-b246-b0a9de3f4056”
  content/src/exercises/0e663e57-e320-4ec2-b246-b0a9de3f4056.json
Labels: decap-cms/pending_publish

#5462 Update Exercise “4ade5d0d-6959-4ba6-9b0c-d98aef65b754”
  content/src/exercises/4ade5d0d-6959-4ba6-9b0c-d98aef65b754.json
Labels: decap-cms/pending_publish

#5465 Update Collection “74c65a83-449f-4ff1-97e1-e6f3c443e40b”
  content/src/collections/74c65a83-449f-4ff1-97e1-e6f3c443e40b.json
Labels: decap-cms/pending_publish

#5367 Create Exercise “9d86dfa5-c0ed-49bb-856d-8185a017785e”
  content/src/exercises/9d86dfa5-c0ed-49bb-856d-8185a017785e.json
Labels: decap-cms/pending_publish

#5318 Create Exercise “023ad824-8009-4667-b148-13d0e966ffd2”
  content/src/exercises/023ad824-8009-4667-b148-13d0e966ffd2.json
Labels: decap-cms/pending_publish

#5319 Create Exercise “4ffe2765-995a-4afc-ae86-65d08088915b”
  content/src/exercises/4ffe2765-995a-4afc-ae86-65d08088915b.json
Labels: decap-cms/pending_publish

#5363 Create Exercise “a1da8d37-0330-4611-ad1b-f65d08f71d2e”
  content/src/exercises/a1da8d37-0330-4611-ad1b-f65d08f71d2e.json
Labels: decap-cms/pending_publish

#5321 Create Exercise “881edc87-02f4-4543-9f32-7c4b5ef34c94”
  content/src/exercises/881edc87-02f4-4543-9f32-7c4b5ef34c94.json
Labels: decap-cms/pending_publish

#5320 Create Exercise “85b2fb9a-68ca-4094-8645-c4bd17e43229”
  content/src/exercises/85b2fb9a-68ca-4094-8645-c4bd17e43229.json
Labels: decap-cms/pending_publish

#5375 Create Exercise “9451652d-444f-4e96-86cc-dcb774ab6c27”
  content/src/exercises/9451652d-444f-4e96-86cc-dcb774ab6c27.json
Labels: decap-cms/pending_publish

#5466 Update Exercise “fff6f8da-f69c-458f-8905-acee04bd1a1d”
  content/src/exercises/fff6f8da-f69c-458f-8905-acee04bd1a1d.json
Labels: decap-cms/pending_publish

#5467 Update Exercise “9451652d-444f-4e96-86cc-dcb774ab6c27”
  content/src/exercises/9451652d-444f-4e96-86cc-dcb774ab6c27.json
Labels: decap-cms/pending_publish

#5468 Create Collection “825ff6a2-81dd-448c-ace2-dbd69c155aa6”
  content/src/collections/825ff6a2-81dd-448c-ace2-dbd69c155aa6.json
Labels: decap-cms/pending_publish

#5470 Create Collection “6524d27e-2a79-48c0-b4aa-dea830231062”
  content/src/collections/6524d27e-2a79-48c0-b4aa-dea830231062.json
Labels: decap-cms/pending_publish

#5335 Update Collection “12c07699-0129-4f9a-aab2-564e45d81484”
  content/src/collections/12c07699-0129-4f9a-aab2-564e45d81484.json
Labels: decap-cms/pending_publish

#5475 Update Collection “12c07699-0129-4f9a-aab2-564e45d81484”
  content/src/collections/12c07699-0129-4f9a-aab2-564e45d81484.json
Labels: decap-cms/pending_publish

#5474 Update Collection “825ff6a2-81dd-448c-ace2-dbd69c155aa6”
  content/src/collections/825ff6a2-81dd-448c-ace2-dbd69c155aa6.json
Labels: decap-cms/pending_publish

#5473 Update Exercise “0bcb6eb0-fdfe-466d-8603-ae6de15fcbc5”
  content/src/exercises/0bcb6eb0-fdfe-466d-8603-ae6de15fcbc5.json
Labels: decap-cms/pending_publish

#5476 Update Exercise “61adeaf2-70ab-4c6c-854c-2c16f762a3c5”
  content/src/exercises/61adeaf2-70ab-4c6c-854c-2c16f762a3c5.json
Labels: decap-cms/pending_publish

#5477 Update Collection “74c65a83-449f-4ff1-97e1-e6f3c443e40b”
  content/src/collections/74c65a83-449f-4ff1-97e1-e6f3c443e40b.json
Labels: decap-cms/pending_publish

#5480 Update 🪴 Other “featured”
  content/src/featured/content.json
Labels: decap-cms/draft
