Repository 29ki/29k, pull requests merged in 2024-02, with the labels that each got.

#4650 🚢 Release 2.45.0
  client/android/app/build.gradle
  client/ios/Podfile.lock
  client/ios/Supporting/Info.plist
  client/ios/twentyninek.xcodeproj/project.pbxproj
  client/package.json
  client/yarn.lock
Labels: native release

#4671 P5.js portal support
  client/ios/Podfile.lock
  client/package.json
  client/src/lib/components/Icons/Pause/Pause.tsx
  client/src/lib/components/MediaControls/MediaControls.tsx
  client/src/lib/session/components/ContentControls/ContentControls.tsx
  client/src/lib/session/components/IntroPortal/IntroPortal.tsx
  client/src/lib/session/components/OutroPortal/OutroPortal.tsx
  client/src/lib/session/components/P5Animation/P5Animation.tsx
  client/src/lib/session/components/P5Animation/P5Animation.web.tsx
  client/src/lib/session/components/P5Animation/p5HtmlTemplate.ts
  client/src/lib/session/components/P5Animation/p5js.ts
  client/src/lib/session/components/Slides/Slide.tsx
  client/src/lib/session/components/Slides/Slides/Content.tsx
  client/src/lib/session/components/Slides/Slides/Instruction.tsx
  client/src/routes/modals/CalmDownModal/CalmDownModal.tsx
  client/src/routes/screens/AsyncSession/IntroPortal.tsx
  client/src/routes/screens/LiveSession/IntroPortal.tsx
  client/yarn.lock
  cms/src/fields/category.ts
  cms/src/fields/common.ts
  cms/src/fields/exercise.ts
  cms/src/previews/Exercise.tsx
  cms/src/previews/components/PortalP5.tsx
  cms/src/previews/components/PortalVideo.tsx
  content/exportToCsv.ts
  shared/src/types/Content.ts
  shared/src/types/generated/Exercise.ts
Labels: native release

#4714 Update 🪴 Other “all-contributorsrc”
  .all-contributorsrc
Labels: decap-cms/pending_publish

#4715 Update Exercise “c1c4da35-87af-4e10-a8d9-e6c58571f724”
  content/src/exercises/c1c4da35-87af-4e10-a8d9-e6c58571f724.json
Labels: decap-cms/pending_publish

#4672 🚢 Release 2.46.0
  client/android/app/build.gradle
  client/ios/Podfile.lock
  client/ios/Supporting/Info.plist
  client/ios/twentyninek.xcodeproj/project.pbxproj
  client/package.json
  client/src/lib/session/components/IntroPortal/IntroPortal.tsx
  client/src/lib/session/components/OutroPortal/OutroPortal.tsx
  client/src/lib/session/components/P5Animation/P5Animation.tsx
  client/src/routes/screens/AsyncSession/IntroPortal.tsx
  client/src/routes/screens/LiveSession/IntroPortal.tsx
  client/yarn.lock
Labels: native release

#4716 Create Exercise “f59b7f66-43b0-4b50-9afe-91092d7dc469”
  content/src/exercises/f59b7f66-43b0-4b50-9afe-91092d7dc469.json
Labels: decap-cms/pending_publish

#4719 Create Collection “b77e52b5-c927-4178-ba76-8c3fe3dbf13c”
  content/src/collections/b77e52b5-c927-4178-ba76-8c3fe3dbf13c.json
Labels: decap-cms/pending_publish

#4718 Update Collection “d9897547-18a2-4404-b12b-324458021783”
  content/src/collections/d9897547-18a2-4404-b12b-324458021783.json
Labels: decap-cms/pending_publish

#4745 Update Exercise “33a188a2-6871-47d6-a754-f5c246bd6b9a”
  content/src/exercises/33a188a2-6871-47d6-a754-f5c246bd6b9a.json
Labels: decap-cms/pending_publish

#4751 Update Exercise “f59b7f66-43b0-4b50-9afe-91092d7dc469”
  content/src/exercises/f59b7f66-43b0-4b50-9afe-91092d7dc469.json
Labels: decap-cms/pending_publish

#4750 Update Exercise “c1c4da35-87af-4e10-a8d9-e6c58571f724”
  content/src/exercises/c1c4da35-87af-4e10-a8d9-e6c58571f724.json
Labels: decap-cms/pending_publish

#4749 Update Exercise “b1e6cc8e-03a4-4f74-8884-2896c391ab07”
  content/src/exercises/b1e6cc8e-03a4-4f74-8884-2896c391ab07.json
Labels: decap-cms/pending_publish

#4755 Update Exercise “f59b7f66-43b0-4b50-9afe-91092d7dc469”
  content/src/exercises/f59b7f66-43b0-4b50-9afe-91092d7dc469.json
Labels: decap-cms/pending_publish

#4753 Update Exercise “b1e6cc8e-03a4-4f74-8884-2896c391ab07”
  content/src/exercises/b1e6cc8e-03a4-4f74-8884-2896c391ab07.json
Labels: decap-cms/pending_publish

#4752 Update Exercise “33a188a2-6871-47d6-a754-f5c246bd6b9a”
  content/src/exercises/33a188a2-6871-47d6-a754-f5c246bd6b9a.json
Labels: decap-cms/pending_publish

#4756 Update Exercise “c1c4da35-87af-4e10-a8d9-e6c58571f724”
  content/src/exercises/c1c4da35-87af-4e10-a8d9-e6c58571f724.json
Labels: decap-cms/pending_publish

#4760 Update Exercise “f59b7f66-43b0-4b50-9afe-91092d7dc469”
  content/src/exercises/f59b7f66-43b0-4b50-9afe-91092d7dc469.json
Labels: decap-cms/pending_publish

#4759 Update Exercise “c1c4da35-87af-4e10-a8d9-e6c58571f724”
  content/src/exercises/c1c4da35-87af-4e10-a8d9-e6c58571f724.json
Labels: decap-cms/pending_publish

#4758 Update Exercise “b1e6cc8e-03a4-4f74-8884-2896c391ab07”
  content/src/exercises/b1e6cc8e-03a4-4f74-8884-2896c391ab07.json
Labels: decap-cms/pending_publish

#4757 Update Exercise “33a188a2-6871-47d6-a754-f5c246bd6b9a”
  content/src/exercises/33a188a2-6871-47d6-a754-f5c246bd6b9a.json
Labels: decap-cms/pending_publish

#4761 Update Exercise “c1c4da35-87af-4e10-a8d9-e6c58571f724”
  content/src/exercises/c1c4da35-87af-4e10-a8d9-e6c58571f724.json
Labels: decap-cms/pending_publish

#4762 Create Exercise “648e1802-eb45-47b0-a42e-dd986669a4eb-1”
  content/src/exercises/648e1802-eb45-47b0-a42e-dd986669a4eb-1.json
Labels: decap-cms/pending_publish

#4763 Create Exercise “5b69ff57-10c4-4288-afc7-a6f6ed212531-1”
  content/src/exercises/5b69ff57-10c4-4288-afc7-a6f6ed212531-1.json
Labels: decap-cms/pending_publish

#4765 Create Exercise “b7f8731c-64d7-4c0f-9bc8-a3e50ec2eaf7-1”
  content/src/exercises/b7f8731c-64d7-4c0f-9bc8-a3e50ec2eaf7-1.json
Labels: decap-cms/pending_publish

#4764 Create Exercise “c7911238-ca9f-4499-9cae-63dfcd0c79c5-1”
  content/src/exercises/c7911238-ca9f-4499-9cae-63dfcd0c79c5-1.json
Labels: decap-cms/pending_publish

#4766 Create Exercise “fff6f8da-f69c-458f-8905-acee04bd1a1d-1”
  content/src/exercises/fff6f8da-f69c-458f-8905-acee04bd1a1d-1.json
Labels: decap-cms/pending_publish

#4767 Create Collection “2e60ad26-dc5c-46bd-b39e-b7210f1a4e32”
  content/src/collections/2e60ad26-dc5c-46bd-b39e-b7210f1a4e32.json
Labels: decap-cms/pending_publish

#4717 🚢 Release 2.47.0
  client/android/app/build.gradle
  client/fastlane/Gemfile.lock
  client/fastlane/Matchfile
  client/ios/Podfile.lock
  client/ios/Supporting/Info.plist
  client/ios/production.entitlements
  client/ios/staging.entitlements
  client/ios/twentyninek.xcodeproj/project.pbxproj
  client/package.json
  client/yarn.lock
Labels: native release

#4812 Update Exercise “9d2ae09f-274b-4fd6-bc3c-8a4576c45c37”
  content/src/exercises/9d2ae09f-274b-4fd6-bc3c-8a4576c45c37.json
Labels: decap-cms/pending_publish

#4813 Update Exercise “d8629c6f-76af-47a1-ab92-209009234ff2”
  content/src/exercises/d8629c6f-76af-47a1-ab92-209009234ff2.json
Labels: decap-cms/pending_publish

#4820 Update Exercise “ab3c3bc4-5586-4554-aa93-ebe7d6910741”
  content/src/exercises/ab3c3bc4-5586-4554-aa93-ebe7d6910741.json
Labels: decap-cms/pending_publish

#4823 Update Exercise “3f4710a6-1fc9-45c3-b636-d18f31a2d751”
  content/src/exercises/3f4710a6-1fc9-45c3-b636-d18f31a2d751.json
Labels: decap-cms/pending_publish

#4827 Update 🪴 Other “featured”
  content/src/featured/content.json
Labels: decap-cms/draft

#4835 Update Exercise “26a58ed8-0adf-4460-8d9c-a5859364c26b”
  content/src/exercises/26a58ed8-0adf-4460-8d9c-a5859364c26b.json
Labels: decap-cms/pending_publish

#4832 🚢 Release 2.48.1
  client/android/app/build.gradle
  client/ios/Podfile.lock
  client/ios/Supporting/Info.plist
  client/ios/twentyninek.xcodeproj/project.pbxproj
  client/package.json
  client/yarn.lock
Labels: native release

#4870 Update Collection “2e60ad26-dc5c-46bd-b39e-b7210f1a4e32”
  content/src/collections/2e60ad26-dc5c-46bd-b39e-b7210f1a4e32.json
Labels: decap-cms/pending_publish

#4871 Update Collection “2e60ad26-dc5c-46bd-b39e-b7210f1a4e32”
  content/src/collections/2e60ad26-dc5c-46bd-b39e-b7210f1a4e32.json
Labels: decap-cms/pending_publish

#4872 Update Collection “2e60ad26-dc5c-46bd-b39e-b7210f1a4e32”
  content/src/collections/2e60ad26-dc5c-46bd-b39e-b7210f1a4e32.json
Labels: decap-cms/pending_publish

#4875 Update Exercise “d8629c6f-76af-47a1-ab92-209009234ff2”
  content/src/exercises/d8629c6f-76af-47a1-ab92-209009234ff2.json
Labels: decap-cms/pending_publish

#4864 Update Exercise “26a58ed8-0adf-4460-8d9c-a5859364c26b”
  content/src/exercises/26a58ed8-0adf-4460-8d9c-a5859364c26b.json
Labels: decap-cms/pending_publish

#4865 Update Exercise “3f4710a6-1fc9-45c3-b636-d18f31a2d751”
  content/src/exercises/3f4710a6-1fc9-45c3-b636-d18f31a2d751.json
Labels: decap-cms/pending_publish

#4866 Update Exercise “9d2ae09f-274b-4fd6-bc3c-8a4576c45c37”
  content/src/exercises/9d2ae09f-274b-4fd6-bc3c-8a4576c45c37.json
Labels: decap-cms/pending_publish

#4882 Update Collection “2e60ad26-dc5c-46bd-b39e-b7210f1a4e32”
  content/src/collections/2e60ad26-dc5c-46bd-b39e-b7210f1a4e32.json
Labels: decap-cms/pending_publish

#4885 Update Exercise “3f4710a6-1fc9-45c3-b636-d18f31a2d751”
  content/src/exercises/3f4710a6-1fc9-45c3-b636-d18f31a2d751.json
Labels: decap-cms/pending_publish

#4883 Update Exercise “9d2ae09f-274b-4fd6-bc3c-8a4576c45c37”
  content/src/exercises/9d2ae09f-274b-4fd6-bc3c-8a4576c45c37.json
Labels: decap-cms/pending_publish

#4880 Update Exercise “ab3c3bc4-5586-4554-aa93-ebe7d6910741”
  content/src/exercises/ab3c3bc4-5586-4554-aa93-ebe7d6910741.json
Labels: decap-cms/pending_publish

#4879 Update Exercise “d8629c6f-76af-47a1-ab92-209009234ff2”
  content/src/exercises/d8629c6f-76af-47a1-ab92-209009234ff2.json
Labels: decap-cms/pending_publish

#4884 Update Collection “2e60ad26-dc5c-46bd-b39e-b7210f1a4e32”
  content/src/collections/2e60ad26-dc5c-46bd-b39e-b7210f1a4e32.json
Labels: decap-cms/pending_publish

#4877 Update Exercise “26a58ed8-0adf-4460-8d9c-a5859364c26b”
  content/src/exercises/26a58ed8-0adf-4460-8d9c-a5859364c26b.json
Labels: decap-cms/pending_publish

#4886 Update Exercise “3f4710a6-1fc9-45c3-b636-d18f31a2d751”
  content/src/exercises/3f4710a6-1fc9-45c3-b636-d18f31a2d751.json
Labels: decap-cms/pending_publish

#4887 Update Collection “2e60ad26-dc5c-46bd-b39e-b7210f1a4e32”
  content/src/collections/2e60ad26-dc5c-46bd-b39e-b7210f1a4e32.json
Labels: decap-cms/pending_publish

#4889 Update Exercise “3f4710a6-1fc9-45c3-b636-d18f31a2d751”
  content/src/exercises/3f4710a6-1fc9-45c3-b636-d18f31a2d751.json
Labels: decap-cms/pending_publish

#4890 Update Collection “2e60ad26-dc5c-46bd-b39e-b7210f1a4e32”
  content/src/collections/2e60ad26-dc5c-46bd-b39e-b7210f1a4e32.json
Labels: decap-cms/pending_publish

#4891 Update Collection “2e60ad26-dc5c-46bd-b39e-b7210f1a4e32”
  content/src/collections/2e60ad26-dc5c-46bd-b39e-b7210f1a4e32.json
Labels: decap-cms/pending_publish
