Repository 29ki/29k, pull requests merged in 2025-02, with the labels that each got.

#6619 Update Exercise “3adeb40b-b9f8-4b13-b1a8-02f6106df9e5”
  content/src/exercises/3adeb40b-b9f8-4b13-b1a8-02f6106df9e5.json
Labels: decap-cms/pending_publish

#6618 Update Exercise “b9001702-8502-46de-bc7b-3ebf2b812c0e”
  content/src/exercises/b9001702-8502-46de-bc7b-3ebf2b812c0e.json
Labels: decap-cms/pending_publish

#6620 Update Exercise “3adeb40b-b9f8-4b13-b1a8-02f6106df9e5”
  content/src/exercises/3adeb40b-b9f8-4b13-b1a8-02f6106df9e5.json
Labels: decap-cms/pending_publish

#6621 Update Exercise “f2c88307-b02e-4456-a81c-79b84c10ae04”
  content/src/exercises/f2c88307-b02e-4456-a81c-79b84c10ae04.json
Labels: decap-cms/pending_publish

#6615 Update Exercise “19135d2e-0e8d-418c-939d-18b0e62215ff”
  content/src/exercises/19135d2e-0e8d-418c-939d-18b0e62215ff.json
Labels: decap-cms/draft

#6616 Update Exercise “1e96f73b-8193-4aa6-a52c-31355eac3c08”
  content/src/exercises/1e96f73b-8193-4aa6-a52c-31355eac3c08.json
Labels: decap-cms/draft

#6629 Update Exercise “b9001702-8502-46de-bc7b-3ebf2b812c0e”
  content/src/exercises/b9001702-8502-46de-bc7b-3ebf2b812c0e.json
Labels: decap-cms/pending_publish

#6637 Update 📱 UI “Component.Card”
  content/src/ui/Component.Card.json
Labels: decap-cms/pending_publish

#6638 Update 📱 UI “Modal.Session”
  content/src/ui/Modal.Session.json
Labels: decap-cms/pending_publish

#6657 Update Exercise “b491901c-37f8-48a7-829e-feb29a67a459”
  content/src/exercises/b491901c-37f8-48a7-829e-feb29a67a459.json
Labels: decap-cms/pending_publish

#6639 Update 📱 UI “Component.Card”
  content/src/ui/Component.Card.json
Labels: decap-cms/draft

#6660 Update 📱 UI “Modal.Session”
  content/src/ui/Modal.Session.json
Labels: decap-cms/draft

#6659 Update 📱 UI “Component.Card”
  content/src/ui/Component.Card.json
Labels: decap-cms/draft

#6658 Update Exercise “e52b3b32-f2a2-4d09-a3b1-4a186998c980”
  content/src/exercises/e52b3b32-f2a2-4d09-a3b1-4a186998c980.json
Labels: decap-cms/pending_publish

#6666 Update Exercise “ed06daef-cecd-47d8-8ff2-3cf8dba65b6c”
  content/src/exercises/ed06daef-cecd-47d8-8ff2-3cf8dba65b6c.json
Labels: decap-cms/pending_publish

#6663 Update Exercise “dc38ce25-e0f3-465f-8df0-70b5f5089ce9”
  content/src/exercises/dc38ce25-e0f3-465f-8df0-70b5f5089ce9.json
Labels: decap-cms/pending_publish

#6667 Update Exercise “ba239e50-27f5-4a01-8daf-14b76edb7097”
  content/src/exercises/ba239e50-27f5-4a01-8daf-14b76edb7097.json
Labels: decap-cms/pending_publish

#6669 Update Exercise “e52b3b32-f2a2-4d09-a3b1-4a186998c980”
  content/src/exercises/e52b3b32-f2a2-4d09-a3b1-4a186998c980.json
Labels: decap-cms/pending_publish

#6668 Update Exercise “ed06daef-cecd-47d8-8ff2-3cf8dba65b6c”
  content/src/exercises/ed06daef-cecd-47d8-8ff2-3cf8dba65b6c.json
Labels: decap-cms/pending_publish

#6672 Update Exercise “b9001702-8502-46de-bc7b-3ebf2b812c0e”
  content/src/exercises/b9001702-8502-46de-bc7b-3ebf2b812c0e.json
Labels: decap-cms/pending_publish

#6690 Update Exercise “4161a0d8-55ee-4866-a9be-263c85fafd70”
  content/src/exercises/4161a0d8-55ee-4866-a9be-263c85fafd70.json
Labels: decap-cms/pending_publish

#6691 Update Exercise “19573b9a-e2f2-4bba-9687-35d261cbbf49”
  content/src/exercises/19573b9a-e2f2-4bba-9687-35d261cbbf49.json
Labels: decap-cms/pending_publish

#6692 Update Exercise “e52b3b32-f2a2-4d09-a3b1-4a186998c980”
  content/src/exercises/e52b3b32-f2a2-4d09-a3b1-4a186998c980.json
Labels: decap-cms/pending_publish

#6693 Update Exercise “b6de2e28-325e-4ce1-8894-09ac12a6c19f”
  content/src/exercises/b6de2e28-325e-4ce1-8894-09ac12a6c19f.json
Labels: decap-cms/pending_publish

#6694 Update Exercise “ba239e50-27f5-4a01-8daf-14b76edb7097”
  content/src/exercises/ba239e50-27f5-4a01-8daf-14b76edb7097.json
Labels: decap-cms/pending_publish

#6695 Update Exercise “ed06daef-cecd-47d8-8ff2-3cf8dba65b6c”
  content/src/exercises/ed06daef-cecd-47d8-8ff2-3cf8dba65b6c.json
Labels: decap-cms/pending_publish

#6696 Update Exercise “dc38ce25-e0f3-465f-8df0-70b5f5089ce9”
  content/src/exercises/dc38ce25-e0f3-465f-8df0-70b5f5089ce9.json
Labels: decap-cms/pending_publish

#6697 Update Exercise “ed06daef-cecd-47d8-8ff2-3cf8dba65b6c”
  content/src/exercises/ed06daef-cecd-47d8-8ff2-3cf8dba65b6c.json
Labels: decap-cms/pending_publish

#6698 Update Exercise “ba239e50-27f5-4a01-8daf-14b76edb7097”
  content/src/exercises/ba239e50-27f5-4a01-8daf-14b76edb7097.json
Labels: decap-cms/pending_publish

#6699 Update Exercise “b6de2e28-325e-4ce1-8894-09ac12a6c19f”
  content/src/exercises/b6de2e28-325e-4ce1-8894-09ac12a6c19f.json
Labels: decap-cms/pending_publish

#6700 Update Exercise “f2c88307-b02e-4456-a81c-79b84c10ae04”
  content/src/exercises/f2c88307-b02e-4456-a81c-79b84c10ae04.json
Labels: decap-cms/pending_publish

#6705 Update Exercise “e52b3b32-f2a2-4d09-a3b1-4a186998c980”
  content/src/exercises/e52b3b32-f2a2-4d09-a3b1-4a186998c980.json
Labels: decap-cms/pending_publish

#6704 Update Exercise “19573b9a-e2f2-4bba-9687-35d261cbbf49”
  content/src/exercises/19573b9a-e2f2-4bba-9687-35d261cbbf49.json
Labels: decap-cms/pending_publish

#6709 Update Tag “34100e43-2eb8-4d35-8eb0-9fa9f78e4935”
  content/src/tags/34100e43-2eb8-4d35-8eb0-9fa9f78e4935.json
Labels: decap-cms/pending_publish

#6707 Update Collection “5b0305d0-df2c-4ee5-b5ee-366f6709b33d”
  content/src/collections/5b0305d0-df2c-4ee5-b5ee-366f6709b33d.json
Labels: decap-cms/pending_publish

#6710 Update Tag “43a6dc0d-d866-4b79-9453-13c44e906128”
  content/src/tags/43a6dc0d-d866-4b79-9453-13c44e906128.json
Labels: decap-cms/pending_publish

#6708 Update Exercise “19573b9a-e2f2-4bba-9687-35d261cbbf49”
  content/src/exercises/19573b9a-e2f2-4bba-9687-35d261cbbf49.json
Labels: decap-cms/pending_publish

#6712 Update Tag “8da0534a-5da9-430a-bdf3-242ace6460fb”
  content/src/tags/8da0534a-5da9-430a-bdf3-242ace6460fb.json
Labels: decap-cms/pending_publish

#6711 Update Tag “566aeb1b-1649-4f5a-96a2-0c80be27efc0”
  content/src/tags/566aeb1b-1649-4f5a-96a2-0c80be27efc0.json
Labels: decap-cms/pending_publish

#6714 Update Tag “cfc00217-f65b-4a4d-8b82-8ccc8f852dd6”
  content/src/tags/cfc00217-f65b-4a4d-8b82-8ccc8f852dd6.json
Labels: decap-cms/pending_publish

#6715 Update Tag “db34d82a-4c48-4ddd-9de5-f562d8aa1bc9”
  content/src/tags/db34d82a-4c48-4ddd-9de5-f562d8aa1bc9.json
Labels: decap-cms/pending_publish

#6716 Update Exercise “ab3c3bc4-5586-4554-aa93-ebe7d6910741”
  content/src/exercises/ab3c3bc4-5586-4554-aa93-ebe7d6910741.json
Labels: decap-cms/pending_publish

#6717 Update Exercise “19573b9a-e2f2-4bba-9687-35d261cbbf49”
  content/src/exercises/19573b9a-e2f2-4bba-9687-35d261cbbf49.json
Labels: decap-cms/pending_publish

#6718 Update Exercise “f2c88307-b02e-4456-a81c-79b84c10ae04”
  content/src/exercises/f2c88307-b02e-4456-a81c-79b84c10ae04.json
Labels: decap-cms/pending_publish

#6719 Update Exercise “b9001702-8502-46de-bc7b-3ebf2b812c0e”
  content/src/exercises/b9001702-8502-46de-bc7b-3ebf2b812c0e.json
Labels: decap-cms/pending_publish

#6722 Update Exercise “3adeb40b-b9f8-4b13-b1a8-02f6106df9e5”
  content/src/exercises/3adeb40b-b9f8-4b13-b1a8-02f6106df9e5.json
Labels: decap-cms/pending_publish

#6723 Update Exercise “dc38ce25-e0f3-465f-8df0-70b5f5089ce9”
  content/src/exercises/dc38ce25-e0f3-465f-8df0-70b5f5089ce9.json
Labels: decap-cms/pending_publish

#6724 Update Collection “5b0305d0-df2c-4ee5-b5ee-366f6709b33d”
  content/src/collections/5b0305d0-df2c-4ee5-b5ee-366f6709b33d.json
Labels: decap-cms/pending_publish

#6725 Update Exercise “19573b9a-e2f2-4bba-9687-35d261cbbf49”
  content/src/exercises/19573b9a-e2f2-4bba-9687-35d261cbbf49.json
Labels: decap-cms/pending_publish

#6726 Update Exercise “b9001702-8502-46de-bc7b-3ebf2b812c0e”
  content/src/exercises/b9001702-8502-46de-bc7b-3ebf2b812c0e.json
Labels: decap-cms/pending_publish

#6727 Update Exercise “ba239e50-27f5-4a01-8daf-14b76edb7097”
  content/src/exercises/ba239e50-27f5-4a01-8daf-14b76edb7097.json
Labels: decap-cms/pending_publish

#6729 Update Exercise “f2c88307-b02e-4456-a81c-79b84c10ae04”
  content/src/exercises/f2c88307-b02e-4456-a81c-79b84c10ae04.json
Labels: decap-cms/pending_publish

#6728 Update Exercise “b6de2e28-325e-4ce1-8894-09ac12a6c19f”
  content/src/exercises/b6de2e28-325e-4ce1-8894-09ac12a6c19f.json
Labels: decap-cms/pending_publish

#6749 Update Exercise “4161a0d8-55ee-4866-a9be-263c85fafd70”
  content/src/exercises/4161a0d8-55ee-4866-a9be-263c85fafd70.json
Labels: decap-cms/pending_publish

#6750 Update Exercise “3adeb40b-b9f8-4b13-b1a8-02f6106df9e5”
  content/src/exercises/3adeb40b-b9f8-4b13-b1a8-02f6106df9e5.json
Labels: decap-cms/pending_publish

#6752 Update Exercise “19573b9a-e2f2-4bba-9687-35d261cbbf49”
  content/src/exercises/19573b9a-e2f2-4bba-9687-35d261cbbf49.json
Labels: decap-cms/pending_publish

#6757 Update Exercise “dc38ce25-e0f3-465f-8df0-70b5f5089ce9”
  content/src/exercises/dc38ce25-e0f3-465f-8df0-70b5f5089ce9.json
Labels: decap-cms/pending_publish

#6761 Update Exercise “4161a0d8-55ee-4866-a9be-263c85fafd70”
  content/src/exercises/4161a0d8-55ee-4866-a9be-263c85fafd70.json
Labels: decap-cms/pending_publish

#6517 🚢 Release 2.60.0
  .github/workflows/build-android.yml
  .github/workflows/build-ios.yml
  .github/workflows/deploy-revopush.yml
  .github/workflows/main.yml
  client/.env.example
  client/android/app/build.gradle
  client/android/app/src/main/AndroidManifest.xml
  client/android/app/src/main/res/values/strings.xml
  client/fastlane/Gemfile.lock
  client/ios/Podfile.lock
  client/ios/Supporting/Info.plist
  client/ios/twentyninek.xcodeproj/project.pbxproj
  client/jest.config.js
  client/package.json
  client/src/lib/codePush/hooks/useCheckForUpdate.spec.ts
  client/src/lib/codePush/hooks/useCheckForUpdate.ts
  client/types/env.d.ts
  client/yarn.lock
Labels: native release

#6764 Update Exercise “4161a0d8-55ee-4866-a9be-263c85fafd70”
  content/src/exercises/4161a0d8-55ee-4866-a9be-263c85fafd70.json
Labels: decap-cms/pending_publish
